force-app/main/default/objects/ItensNotaFiscal__c/ItensNotaFiscal__c.object-meta.xml
<CustomObject>
    <label>Itens da Nota Fiscal</label>
    <nameField>
        <label>Itens da Nota Fiscal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens das Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ItensNotaFiscal__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotaFiscal__c/NotaFiscal__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal</label>
    <nameField>
        <label>Nota Fiscal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotaFiscal__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotaFiscal__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Número da Nota Fiscal</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IntegrationINInvoiceItens.cls
global with sharing class IntegrationINInvoiceItens {
    public IntegrationINInvoiceItens() {

    }
    global static Map<String, List<TemplateDataIntegrationFields.Response>> upsertInvoiceItens(List<TemplateDataIntegrationFields.ItensNotaFiscalINData> request) {
        // Guarda as relações de order e product de preço com OrderItem
        Map<String, Id> lookups = new Map<String, Id>();

        //Set<String> orderLookups = new Set<String>();
        Set<String> productLookups = new Set<String>();
        Set<String> invoiceLookups = new Set<String>();
        // Guarda um mapa com uma lista de respostas
        Map<String, List<TemplateDataIntegrationFields.Response>> responseMap = new Map<String, List<TemplateDataIntegrationFields.Response>>();
        // Guarda uma lista com os OrderItem para fazer o upsert
        List<ItensNotaFiscal__c> invoiceItensListToUpsert = new List<ItensNotaFiscal__c>();

        //Application of business rules
        for(TemplateDataIntegrationFields.ItensNotaFiscalINData itensNotaFiscal : request){

            // Pega a relação do OrderItem com Order
            //Getting order parameters to search
            //orderLookups.add(OrderItemINData.orderExternalId);

            // Pega a relação do Product com o OrderItem
            //Getting product parameters to search
            productLookups.add(itensNotaFiscal.codigoMaterial);
            invoiceLookups.add(itensNotaFiscal.notaFiscal);
        }

        // Pega o produto com base no ExternalID recebido
        //Product2 search based on ExternalId__c field sent
        for (Product2 product : [SELECT Id,ProductCode FROM Product2 WHERE ProductCode IN: productLookups ]) {
            //Map structure for the model -> object name + parameter to record id
            lookups.put('Product2' + product.ProductCode, product.Id);
        }
        for (NotaFiscal__c invoice : [SELECT Id, invoiceNumber__c, ExternalID__c FROM NotaFiscal__c WHERE invoiceNumber__c IN: invoiceLookups]){
          lookups.put('NotaFiscal__c' + invoice.invoiceNumber__c, invoice.Id);
        }
        // Pega o pedido com base no ExternalId recebido
        //Order search based on ExternalId__c field sent

        // Associa as respostas do OrderItem com Order
        //OrderItem ExternalId Map to Order ExternalId for association of responses
        Map<String, String> parentMapKeys = new Map<String, String>();
        
        for(TemplateDataIntegrationFields.ItensNotaFiscalINData invoiceItem : request) {
            // como estava = parentMapKeys.put(ORDEREXTERNALID + '|' + ORDERITEMEXTERNALID, lookups.containsKey('Order'+ORDEREXTERNALID) ? lookups.get('Order'+ORDEREXTERNALID) : ORDEREXTERNALID);
            //parentMapKeys.put(invoiceItem.nfExternalId + '|' + invoiceItem.notaFiscal, lookups.containsKey('NotaFiscal__c'+invoiceItem.nfExternalId) ? String.valueOf(lookups.get('NotaFiscal__c'+invoiceItem.nfExternalId)) : invoiceItem.nfExternalId);
        }
        
        // Valida e adiciona os OrderItem na lista para o upsert
        //Converting template to object list and validating required fields
        FactoryDataIntegration.convertSObjectChild(
            new ItensNotaFiscal__c(), 
            'IN', 
            request, 
            responseMap, 
            invoiceItensListToUpsert, 
            lookups, 
            parentMapKeys
        );

        //Upserting records
        List<Database.UpsertResult> upsResults = Database.upsert(invoiceItensListToUpsert, ItensNotaFiscal__c.ExternalID__c, false);

        IntegrationUtils.upsertChildRecords(upsResults, responseMap, invoiceItensListToUpsert, ItensNotaFiscal__c.ExternalID__c); 
        system.debug('invoiceItensListToUpsert' + invoiceItensListToUpsert);
        system.debug('ItensNotaFiscal__c.ExternalID__c' + ItensNotaFiscal__c.ExternalID__c);
        //Returning response
        return responseMap;
    }
}