force-app/main/default/objects/GeneralQuotas__c/GeneralQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Geral</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Atenção: ao selecionar a quantidade, verifique a unidade de medida clicando no produto para que seja disponibilizado a quantidade correta!</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/IndividualQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Individual</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Individuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IndividualQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/GeneralQuotas__c.field-meta.xml
<CustomField>
    <fullName>GeneralQuotas__c</fullName>
    <label>Cota Geral (Saldo Macro)</label>
    <referenceTo>GeneralQuotas__c</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IndividualQuotasHelper.cls
public without sharing class IndividualQuotasHelper {
    private static Boolean isEnabled;

    static {
        isEnabled = true;
    }

    public static Boolean isTriggerEnabled() {
        return isEnabled;
    }
    
    public static Boolean disableTrigger() {
        return isEnabled = false;
    }

    public static Boolean enableTrigger() {
        return isEnabled = true;
    }

    public static void changeGeneralValues(List<IndividualQuotas__c> newRecords, Map<Id, IndividualQuotas__c> oldMap) {
        Set<Id> generalQuotasIds = new Set<Id>();
        for (IndividualQuotas__c individualQuotes : newRecords) {
            generalQuotasIds.add(individualQuotes.GeneralQuotas__c);
        }

        Map<Id, GeneralQuotas__c> generalQuotasById = new Map<Id, GeneralQuotas__c>();
        for (GeneralQuotas__c generalQuota : [
            SELECT Id,
                   Balance__c,
                   Consumed__c,
                   Quantity__c
              FROM GeneralQuotas__c
             WHERE Id IN: generalQuotasIds
        ]) {
            generalQuotasById.put(generalQuota.Id, generalQuota);
        }

        Boolean quantityError = false;
        for (IndividualQuotas__c individualQuotes : newRecords) {
            individualQuotes.Balance__c = individualQuotes.Quantity__c - (individualQuotes.Consumed__c == null ? 0 : individualQuotes.Consumed__c);
            GeneralQuotas__c generalQuota = generalQuotasById.get(individualQuotes.GeneralQuotas__c);
            
            if (oldMap != null) {
                IndividualQuotas__c oldValues = oldMap.get(individualQuotes.Id);
                generalQuota.Consumed__c = (generalQuota.Consumed__c == null ? 0 : generalQuota.Consumed__c) + individualQuotes.Quantity__c - oldValues.Quantity__c;
                generalQuota.Balance__c = generalQuota.Balance__c - individualQuotes.Quantity__c + oldValues.Quantity__c;

                if (generalQuota.Consumed__c < 0 || generalQuota.Balance__c < 0) {
                    individualQuotes.addError('As quantidades da cota geral precisam ser respeitadas');
                    quantityError = true;
                }
            } else {
                generalQuota.Consumed__c = (generalQuota.Consumed__c == null ? 0 : generalQuota.Consumed__c) + individualQuotes.Quantity__c;
                generalQuota.Balance__c = generalQuota.Balance__c - individualQuotes.Quantity__c;
            }
            generalQuotasById.put(generalQuota.Id, generalQuota);
        }

        if (!quantityError) {
            GeneralQuotasTriggerHelper.disableTrigger();
            update generalQuotasById.values();
            GeneralQuotasTriggerHelper.enableTrigger();
        }
    }
}