force-app/main/default/objects/GeneralQuotas__c/GeneralQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Geral</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Atenção: ao selecionar a quantidade, verifique a unidade de medida clicando no produto para que seja disponibilizado a quantidade correta!</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/IndividualQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Individual</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Individuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IndividualQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/GeneralQuotas__c.field-meta.xml
<CustomField>
    <fullName>GeneralQuotas__c</fullName>
    <label>Cota Geral (Saldo Macro)</label>
    <referenceTo>GeneralQuotas__c</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsOrderMother__c.field-meta.xml
<CustomField>
    <fullName>IsOrderMother__c</fullName>
    <defaultValue>false</defaultValue>
    <label>É Pedido Mãe?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido Mãe</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos Filhos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IndividualQuotas__c.field-meta.xml
<CustomField>
    <fullName>IndividualQuotas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cota Individual</label>
    <referenceTo>IndividualQuotas__c</referenceTo>
    <relationshipLabel>Produto do Pedido</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ItemBalance__c.field-meta.xml
<CustomField>
    <fullName>ItemBalance__c</fullName>
    <label>Saldo do Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ReasonRefuse__c.field-meta.xml
<CustomField>
    <fullName>ReasonRefuse__c</fullName>
    <label>Motivo de Recusa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ReasonRefuse</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderItemHelper.cls
public without sharing class OrderItemHelper {
    
    private static Boolean isEnabled;
    static{
        isEnabled = true;
    }
    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }
    public static Boolean enableTrigger(){
        return isEnabled = true;
    }
    public static void updateOrderItem (List<OrderItem> orderItemList, Map<Id, OrderItem> oldRequest){
        List<String> ordList = new List<String>();
        List<String> orderList = new List<String>();
        List<OrderItem> orderItemListM = new List<OrderItem>();
        for(OrderItem ord : orderItemList){
            orderList.add(ord.OrderId);
        }
        List<Order> orderIdList = new List<Order>([SELECT Id, OrderReference__c, IsOrderMother__c FROM Order WHERE Id =: orderList]);
        Map<String, Order> ordIdMap = New Map<String, Order>();
        for(Order ordIds : orderIdList){
            ordIdMap.put(ordIds.Id, ordIds);
            System.debug('ordIdMap ' + ordIdMap);
        }
        for(OrderItem ordIt : orderItemList){
            Order ord = ordIdMap.get(ordIt.OrderId);
            
            OrderItem oldOrdIt = new OrderItem();
            oldOrdIt = oldRequest.get(ordIt.id);
            System.debug('OrderReference__c ' + ord);
            System.debug('teste'+ ordIt.Order.IsOrderMother__c);
            if(ordIt.Order.IsOrderMother__c != true && ord.OrderReference__c != null){
                System.debug('Entrou no IF');
                System.debug('OrderReference__c ' + ordIt.Order.OrderReference__c);
                ordList.add(ord.OrderReference__c);
                System.debug('ordList ' + ordList);
                //ordIt.Quantity =  ordIt.Quantity - ordIt.ItemBalance__c; 
            }
        }
        List<AggregateResult> sumQuantityPerOrderItem = [SELECT Order.OrderReference__c, Product2.Id, SUM(Quantity) FROM OrderItem WHERE Order.OrderReference__c IN: ordList AND Order.Status != 'X' AND Order.Status != '0' AND ReasonRefuse__c = null GROUP BY Product2.Id,Order.OrderReference__c];
        Map<String, Decimal> orderItemAmountedUsedPerOrderReference = new Map<String, Decimal>();
        for(AggregateResult aggResult : sumQuantityPerOrderItem){
            orderItemAmountedUsedPerOrderReference.put((String)aggResult.get('Id') + (String)aggResult.get('OrderReference__c'), (Decimal)aggResult.get('expr0') );
        }
        List<OrderItem> ordItemList = ([SELECT Id, OrderId, Order.IsOrderMother__c, Product2Id, ItemBalance__c, Quantity  FROM OrderItem WHERE OrderId =: ordList]);
        Map<String, OrderItem> ordMap = new Map<String, OrderItem>();
        for(OrderItem ordItem : ordItemList){
            string concProductOrder = String.valueOf(ordItem.Product2Id) + String.valueOf(ordItem.OrderId);
            System.debug('concatenação ' + concProductOrder);
            System.debug('ordItem' + ordItem);
            ordMap.put(concProductOrder, ordItem);
            System.debug('ordMap' + ordMap);
            
        }
        for(OrderItem ordemItem : orderItemList){
            Order ord = ordIdMap.get(ordemItem.OrderId);
            
            string concProductOrderRef = String.valueOf(ordemItem.Product2Id) + String.valueOf(ord.OrderReference__c);
            System.debug('ordMap Fora ' + ordMap);
            System.debug('concProductOrderRef ' + concProductOrderRef);
            if(ordMap.containsKey(concProductOrderRef)){
                System.debug('ordMap Dentro' + ordMap);
                OrderItem ordrItem = ordMap.get(concProductOrderRef);
                System.debug('ordrItem ' + ordrItem);
                if(ordemItem.Product2Id == ordrItem.Product2Id){
                    System.debug('orderItemListM ' + orderItemListM);
                    OrderItem orddItem = New OrderItem();
                    orddItem.Id = ordrItem.Id;
                    orddItem.ItemBalance__c = orderItemAmountedUsedPerOrderReference.containsKey(concProductOrderRef) ? (ordrItem.Quantity - orderItemAmountedUsedPerOrderReference.get(concProductOrderRef)) : ordrItem.Quantity;
                    // orddItem.ItemBalance__c =  ordemItem.Quantity - ordrItem.ItemBalance__c;
                    // if(orddItem.ItemBalance__c < 0){
                    //     orddItem.ItemBalance__c = orddItem.ItemBalance__c * (-1);                            
                    // } 
                    orderItemListM.add(orddItem);
                    
                }
            }
            
        }
        OrderItemHelper.disableTrigger();
        update orderItemListM;
        OrderItemHelper.enableTrigger();
    }
    public static void updateQuotes(List<OrderItem> orderItemList){
        Set<Id> generalQuotasId = new Set<Id>();
        Set<Id> individualQuotasId = new Set<Id>();
        Set<Id> orderId = new Set<Id>();
        for(OrderItem ordItemForOrder : orderItemList){
            orderId.add(ordItemForOrder.OrderId);
        }
        Map<Id, Order> orderList = new Map<Id, Order>([SELECT id, SalesOrg__c, SalesOrg__r.SalesOrganizationCode__c FROM Order WHERE Id =: orderId]);
    
        for(OrderItem ordItem : orderItemList){
            Order order = orderList.get(ordItem.OrderId);
            if(ordItem.Description != null && ordItem.ReasonRefuse__c != null && ordItem.Description.contains('In73gr ins37t x') && order.SalesOrg__c != null && order.SalesOrg__r.SalesOrganizationCode__c == '1700'){
                individualQuotasId.add(ordItem.IndividualQuotas__c); 
            } 
        }
        
        List<IndividualQuotas__c> individualQuotasList = new List<IndividualQuotas__c>([SELECT id, Quantity__c, Balance__c, Consumed__c, GeneralQuotas__c FROM IndividualQuotas__c WHERE id  =: individualQuotasId]);
        
        for(IndividualQuotas__c indQuotas : individualQuotasList){
            generalQuotasId.add(indQuotas.GeneralQuotas__c); 
        }
        
        List<GeneralQuotas__c> generalQuotasList = new List<GeneralQuotas__c>([SELECT id, Quantity__c,Consumed__c,Balance__c FROM GeneralQuotas__c WHERE Id =: generalQuotasId]);
      
        List<IndividualQuotas__c> individualQuotasListUpdate = new List<IndividualQuotas__c>();
        
        for(IndividualQuotas__c indQuotas : individualQuotasList){
            indQuotas.Balance__c = indQuotas.Quantity__c; 
            
            indQuotas.Consumed__c = 0;
          
            
            IndividualQuotas__c individualQuotas = new IndividualQuotas__c();
          
            individualQuotasListUpdate.add(indQuotas);
        }
        
        OrderItemHelper.disableTrigger();
        upsert individualQuotasListUpdate;
        OrderItemHelper.enableTrigger();
        
        List<IndividualQuotas__c> sumIndividualQuotasList = new List<IndividualQuotas__c>([SELECT id, Quantity__c, Balance__c, Consumed__c, GeneralQuotas__c FROM IndividualQuotas__c WHERE  GeneralQuotas__c =: generalQuotasId]);
        Map<Id, IndividualQuotas__c> individualQuotasMap = new Map<Id, IndividualQuotas__c>();
        Map<Id, Decimal> sumIndividualQuotasMap = new Map<Id, Decimal>();
        
        
        System.debug('sumIndividualQuotasList ' + sumIndividualQuotasList);
        for(IndividualQuotas__c indQuotas : sumIndividualQuotasList){
    
            IndividualQuotas__c individualQuotas = new IndividualQuotas__c();
            if(individualQuotasMap.containsKey(indQuotas.GeneralQuotas__c)){
                individualQuotas = individualQuotasMap.get(indQuotas.GeneralQuotas__c);
                individualQuotas.Consumed__c += indQuotas.Consumed__c;
                
               // individualQuotas.Balance__c += indQuotas.Balance__c;
                individualQuotasMap.put(indQuotas.GeneralQuotas__c, individualQuotas);
            }
            else {
                individualQuotasMap.put(indQuotas.GeneralQuotas__c, indQuotas);
            }
        }
        List<GeneralQuotas__c> generalQuotasListUpdate = new List<GeneralQuotas__c>();
        System.debug('generalQuotasList ' + generalQuotasList);
        for(GeneralQuotas__c generalQuotas: generalQuotasList){
            System.debug('individualQuotasMap ' + individualQuotasMap);
            
                IndividualQuotas__c individualQuotas = individualQuotasMap.get(generalQuotas.Id);
                System.debug('individualQuotas ' + individualQuotas);
                generalQuotas.Consumed__c = individualQuotas.Consumed__c;
                generalQuotas.Balance__c = generalQuotas.Quantity__c - individualQuotas.Consumed__c;
                generalQuotasListUpdate.add(generalQuotas);
               
        }
        
        
        
        
        // OrderItemHelper.disableTrigger();
        // upsert generalQuotasListUpdate;
        // OrderItemHelper.enableTrigger();
    }
    public static void insertOrderItem (List<OrderItem> orderItemList){
        List<String> ordList = new List<String>();
        List<String> orderList = new List<String>();
        List<OrderItem> orderItemListM = new List<OrderItem>();
        
        for(OrderItem ord : orderItemList){
            orderList.add(ord.OrderId);
        }
        List<Order> orderIdList = new List<Order>([SELECT Id, OrderReference__c, IsOrderMother__c FROM Order WHERE Id =: orderList]);
        Map<String, Order> ordIdMap = New Map<String, Order>();
        for(Order ordIds : orderIdList){
            ordIdMap.put(ordIds.Id, ordIds);
            System.debug('ordIdMap ' + ordIdMap);
        }
        for(OrderItem ordIt : orderItemList){
            Order ord = ordIdMap.get(ordIt.OrderId);
            
            System.debug('OrderReference__c ' + ord);
            System.debug('teste'+ ordIt.Order.IsOrderMother__c);                     
            if(ordIt.Description !=null && ordIt.Order.IsOrderMother__c != true && ord.OrderReference__c != null && ordIt.Description.Contains('In73gr ins37t x')){
                System.debug('Entrou no IF');
                System.debug('OrderReference__c ' + ordIt.Order.OrderReference__c);
                ordList.add(ord.OrderReference__c);
                System.debug('ordList ' + ordList);
                //ordIt.Quantity =  ordIt.Quantity - ordIt.ItemBalance__c; 
            }
        }
        List<OrderItem> ordItemList = ([SELECT Id, OrderId, Order.IsOrderMother__c, Product2Id, ItemBalance__c, Quantity  FROM OrderItem WHERE OrderId =: ordList]);
        Map<String, OrderItem> ordMap = new Map<String, OrderItem>();
        for(OrderItem ordItem : ordItemList){
            string concProductOrder = String.valueOf(ordItem.Product2Id) + String.valueOf(ordItem.OrderId);
            System.debug('concatenação ' + concProductOrder);
            System.debug('ordItem' + ordItem);
            ordMap.put(concProductOrder, ordItem);
            System.debug('ordMap' + ordMap);
            
        }
        for(OrderItem ordemItem : orderItemList){
            Order ord = ordIdMap.get(ordemItem.OrderId);
            Decimal calcAmountUsed;
            string concProductOrderRef = String.valueOf(ordemItem.Product2Id) + String.valueOf(ord.OrderReference__c);
            System.debug('ordMap Fora ' + ordMap);
            System.debug('concProductOrderRef ' + concProductOrderRef);
            if(ordMap.containsKey(concProductOrderRef)){
                System.debug('ordMap Dentro' + ordMap);
                OrderItem ordrItem = ordMap.get(concProductOrderRef);
                System.debug('ordrItem ' + ordrItem);
                if(ordemItem.Product2Id == ordrItem.Product2Id){
                    System.debug('orderItemListM ' + orderItemListM);
                    OrderItem orddItem = New OrderItem();
                    orddItem.Id = ordrItem.Id;
                    System.debug('ordemItem.Quantity ' + ordemItem.Quantity);
                    System.debug('ordrItem.ItemBalance__c ' + ordrItem.ItemBalance__c);
                    if(ordrItem.ItemBalance__c != null){
                        calcAmountUsed = ordrItem.ItemBalance__c - ordemItem.Quantity;
                    }
                    else {
                        calcAmountUsed = ordemItem.Quantity;
                    }
                   
                    orddItem.ItemBalance__c =  calcAmountUsed; 
                    orderItemListM.add(orddItem);
                }
            }
        }
        
        OrderItemHelper.disableTrigger();
        upsert orderItemListM;
        OrderItemHelper.enableTrigger();
    }
    public static void cleanDescriptionOrderItem (List<OrderItem> orderItemList){
        List<OrderItem> cleanOrdItemDesc = new List<OrderItem>();
        
        for(OrderItem ordItemClean : orderItemList){
            OrderItem ordItemCl = new OrderItem();
            ordItemCl.Id = ordItemClean.Id;
            if(ordItemClean.Description != null && ordItemClean.Description.contains('In73gr ins37t x')){
                ordItemCl.Description = ordItemClean.Description.replace('In73gr ins37t x', '');
            }
            
            
            cleanOrdItemDesc.add(ordItemCl);
        }
        OrderItemHelper.disableTrigger();
        update cleanOrdItemDesc; 
        OrderItemHelper.enableTrigger();
    }

    public static void conditionsCalc (List<TemplateDataIntegrationFields.OrderItemINData> request, List<TemplateDataIntegrationFields.ConditionInsert> conditionList) {
        
        Decimal porcentagemZCBA;
        Decimal porcentagemZCBI;
        Decimal valorCorretagem;

        for(TemplateDataIntegrationFields.OrderItemINData orderItemsForConditions : request) {
            
            for(TemplateDataIntegrationFields.ConditionInsert  conditionsAssignment : conditionList){
                conditionsAssignment.KPOSN = conditionsAssignment.KPOSN.replaceFirst('^0+','');
                
                if(conditionsAssignment.KPOSN == orderItemsForConditions.orderItemCode){
                    
                    if(conditionsAssignment.KSCHL == 'ZPR0'){
                        orderItemsForConditions.precoUnitario = (Decimal.valueOf(conditionsAssignment.KBETR) / Decimal.valueOf(conditionsAssignment.KPEIN));
                        orderItemsForConditions.precoPraticado = orderItemsForConditions.precoUnitario;
                        System.debug('precoUnitario' + orderItemsForConditions.precoUnitario);
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZDAC'){ //Antigo ZDAN
                        System.debug('conditionsAssignment.KSCHL' + conditionsAssignment.KSCHL);
                       orderItemsForConditions.porcentagemDescontoFin = Decimal.valueOf(conditionsAssignment.KBETR);
                        System.debug('porcentagemDescontoFin' + orderItemsForConditions.porcentagemDescontoFin);
                        
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZJUC'){ //Antigo ZJUR
                        orderItemsForConditions.porcentagemAcrescFin = Decimal.valueOf(conditionsAssignment.KBETR);
                        System.debug('porcentagemAcrescFin' + orderItemsForConditions.porcentagemAcrescFin);
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZMAR'){
                        orderItemsForConditions.margemComercial = Decimal.valueOf(conditionsAssignment.KBETR);
                        System.debug('orderItemsForConditions.margemComercial ' + orderItemsForConditions.margemComercial);
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZFRE'){
                        orderItemsForConditions.freteItem = Decimal.valueOf(conditionsAssignment.KBETR);
                        System.debug('freteItem ' + orderItemsForConditions.freteItem);
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZROY'){
                        orderItemsForConditions.valorZroy = Decimal.valueOf(conditionsAssignment.KBETR);
                        orderItemsForConditions.valorTotalZroy = Decimal.valueOf(conditionsAssignment.KBETR) * orderItemsForConditions.quantidade;
                        System.debug('valorZroy ' + orderItemsForConditions.valorZroy);
                        System.debug('valorTotalZroy ' + orderItemsForConditions.valorTotalZroy);
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZTRA'){
                        orderItemsForConditions.valorZtra = Decimal.valueOf(conditionsAssignment.KBETR);
                        orderItemsForConditions.valorTotalZtra = Decimal.valueOf(conditionsAssignment.KBETR) * orderItemsForConditions.quantidade;
                        System.debug('valorZtra ' + orderItemsForConditions.valorZtra);
                        System.debug('valorTotalZtra ' + orderItemsForConditions.valorTotalZtra);
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZCP0'){
                        Decimal custoPraticado = Decimal.valueOf(conditionsAssignment.KBETR) / orderItemsForConditions.quantidade;
                        orderItemsForConditions.custoPreco = custoPraticado;
                        System.debug('custoPreco ' + orderItemsForConditions.custoPreco);
                    }

                    if(conditionsAssignment.KSCHL == 'ZCOR'){
                        valorCorretagem = Decimal.valueOf(conditionsAssignment.KBETR);
                        
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZCBI'){
                        if(Decimal.valueOf(conditionsAssignment.KBETR) > 0){
                            porcentagemZCBI = Decimal.valueOf(conditionsAssignment.KBETR);
                        }
                        else {
                            porcentagemZCBI = Decimal.valueOf(conditionsAssignment.KBETR) * (-1);
                        }
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZCBA'){
                        if(Decimal.valueOf(conditionsAssignment.KBETR) > 0){
                            porcentagemZCBA = Decimal.valueOf(conditionsAssignment.KBETR); 
                        }
                        else {
                            porcentagemZCBA = Decimal.valueOf(conditionsAssignment.KBETR) * (-1);
                        }
                    }
                    
                    if(conditionsAssignment.KSCHL == 'ZDEC'){
                        orderItemsForConditions.porcentagemAcrescComercial = 0;
                        orderItemsForConditions.porcentagemDesconto = 0;
                        System.debug('KBETR ' + Decimal.valueOf(conditionsAssignment.KBETR));
                        if(Decimal.valueOf(conditionsAssignment.KBETR) > 0){
                            orderItemsForConditions.porcentagemAcrescComercial = Decimal.valueOf(conditionsAssignment.KBETR);
                            System.debug('porcentagemAcrescComercial ' + orderItemsForConditions.porcentagemAcrescComercial);
                        }
                        else {
                            orderItemsForConditions.porcentagemDesconto = Decimal.valueOf(conditionsAssignment.KBETR);
                            orderItemsForConditions.porcentagemDesconto *= (-1);
                            System.debug('porcentagemDesconto ' + orderItemsForConditions.porcentagemDesconto);
                        }
                    }
                    
                }
            }
			

			Decimal valorDescontoFinanceiro = 0;
			Decimal valorAcrescimoFinanceiro = 0;
			Decimal valorDescontoComercial = 0;
            Decimal valorAcrescimoComercial = 0;
            Decimal valorDescontoComboZCBI = 0;
            Decimal valorDescontoComboZCBA = 0;
            Decimal valorFinal = orderItemsForConditions.precoUnitario * orderItemsForConditions.quantidade;
            orderItemsForConditions.valorTotal = valorFinal;
            
            if(orderItemsForConditions.porcentagemDescontoFin > 0){
                valorDescontoFinanceiro = valorFinal * (orderItemsForConditions.porcentagemDescontoFin / 100);
                orderItemsForConditions.valorDescontoFin = valorDescontoFinanceiro;
                valorFinal = valorFinal - valorDescontoFinanceiro; //Bateu
                orderItemsForConditions.precoPraticado = (valorFinal) / orderItemsForConditions.quantidade;
                orderItemsForConditions.valorTotal = valorFinal;
                System.debug('valorFinal ' + valorFinal);
                System.debug('valorDescontoFinanceiro ' + valorDescontoFinanceiro);
            }
            
            if (orderItemsForConditions.porcentagemAcrescFin > 0){
                valorAcrescimoFinanceiro = valorFinal * (orderItemsForConditions.porcentagemAcrescFin / 100);
                orderItemsForConditions.valorAcrescFin = valorAcrescimoFinanceiro;
                valorFinal = valorFinal + valorAcrescimoFinanceiro;
                orderItemsForConditions.precoPraticado = (valorFinal) / orderItemsForConditions.quantidade;
                orderItemsForConditions.valorTotal = valorFinal;
                System.debug('valorFinal ' + valorFinal);
                System.debug('valorAcrescimoFinanceiro ' + valorAcrescimoFinanceiro);
            }
            
            if(porcentagemZCBI > 0){
                valorDescontoComboZCBI = valorFinal * (porcentagemZCBI / 100);
                orderItemsForConditions.valorZCBI = valorDescontoComboZCBI;
                valorFinal = valorFinal - valorDescontoComboZCBI;
                orderItemsForConditions.precoPraticado = (valorFinal) / orderItemsForConditions.quantidade;
                orderItemsForConditions.valorTotal = valorFinal;
                System.debug('ZCBI ' + orderItemsForConditions.valorZCBI);
            }
            
            if(porcentagemZCBA > 0){
                valorDescontoComboZCBA = valorFinal * (porcentagemZCBA / 100);
                orderItemsForConditions.valorZCBA = valorDescontoComboZCBA;
                valorFinal = valorFinal - valorDescontoComboZCBA;
                orderItemsForConditions.precoPraticado = (valorFinal) / orderItemsForConditions.quantidade;
                orderItemsForConditions.valorTotal = valorFinal;
                System.debug('valorZCBA ' + orderItemsForConditions.valorZCBA);
            }
            
            if (orderItemsForConditions.porcentagemDesconto != 0 && orderItemsForConditions.porcentagemDesconto != null){
                valorDescontoComercial = valorFinal  * (orderItemsForConditions.porcentagemDesconto / 100);
                System.debug('porcentagemDesconto ' + (orderItemsForConditions.porcentagemDesconto / 100));
                System.debug('valorDescontoComercial ' + valorDescontoComercial);
                orderItemsForConditions.precoPraticado = (valorFinal - valorDescontoComercial) / orderItemsForConditions.quantidade;
                orderItemsForConditions.valorTotal = (valorFinal - valorDescontoComercial);
                System.debug('valorFinalFinal  ' + orderItemsForConditions.valorTotal);
                orderItemsForConditions.descontoValor = valorDescontoComercial;
            }
            
            if(orderItemsForConditions.porcentagemAcrescComercial != 0 && orderItemsForConditions.porcentagemAcrescComercial != null){
               valorAcrescimoComercial = valorFinal * (orderItemsForConditions.porcentagemAcrescComercial / 100);
               System.debug('valorAcrescimoComercial ' + valorAcrescimoComercial);
               orderItemsForConditions.precoPraticado = (valorFinal + valorAcrescimoComercial) / orderItemsForConditions.quantidade;
               orderItemsForConditions.valorTotal = (valorFinal + valorAcrescimoComercial);
               orderItemsForConditions.valorAcrescComercial = valorAcrescimoComercial;        
            }
            
            System.debug('Valor Final   ' + valorFinal);
            System.debug('valorAcrescComercial  ' + orderItemsForConditions.valorAcrescComercial);
            System.debug('Desconto Valor ' + orderItemsForConditions.descontoValor);
            System.debug('Preço Praticado ' + orderItemsForConditions.precoPraticado);
            if(valorCorretagem != 0 && valorCorretagem != null){
                orderItemsForConditions.valorTotal += valorCorretagem;
            }
            porcentagemZCBA = 0;
            porcentagemZCBI = 0;
            valorCorretagem = 0;
        }
    }
    
}