force-app/main/default/objects/GeneralQuotas__c/GeneralQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Geral</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Cotas Gerais</relationshipLabel>
    <relationshipName>GeneralQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Cultivate__c.field-meta.xml
<CustomField>
    <fullName>Cultivate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cotas Gerais</relationshipLabel>
    <relationshipName>GeneralQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Atenção: ao selecionar a quantidade, verifique a unidade de medida clicando no produto para que seja disponibilizado a quantidade correta!</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/IndividualQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Individual</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Individuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IndividualQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Cultivate__c.field-meta.xml
<CustomField>
    <fullName>Cultivate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/GeneralQuotas__c.field-meta.xml
<CustomField>
    <fullName>GeneralQuotas__c</fullName>
    <label>Cota Geral (Saldo Macro)</label>
    <referenceTo>GeneralQuotas__c</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CTV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IndividualQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GenerateIndividualQuotesController.cls
public without sharing class GenerateIndividualQuotesController {
    @AuraEnabled
    public static String getQuoteData(Id generalQuoteId) {
        GeneralQuotas__c quote = [
            SELECT Id,
                   Crop__c,
                   Crop__r.Name,
                   Cultivate__c,
                   Cultivate__r.Name,
                   Balance__c,
                   Consumed__c,
                   Quantity__c
              FROM GeneralQuotas__c
             WHERE Id =: generalQuoteId
        ];

        QuoteData quoteData = new QuoteData();
        quoteData.quoteId = quote.Id;
        quoteData.cropId = quote.Crop__c;
        quoteData.cropName = quote.Crop__r.Name;
        quoteData.cultivateId = quote.Cultivate__c;
        quoteData.cultivateName = quote.Cultivate__r.Name;
        quoteData.quantity = quote.Quantity__c;
        quoteData.consumed = 0;
        quoteData.balance = quote.Balance__c;
        System.debug('quoteData: ' + generalQuoteId);
        
        return JSON.serialize(quoteData);
    }

    @AuraEnabled
    public static String createIndividualQuote(String individualQuoteData) {
        try {
            QuoteData quoteData = (QuoteData) JSON.deserialize(individualQuoteData, QuoteData.class);
            System.debug('quoteData: ' + quoteData);
            String sellerName = [SELECT Id, Name FROM User WHERE Id =: quoteData.sellerId].Name;

            IndividualQuotas__c individualQuote = new IndividualQuotas__c();
            individualQuote.Name = quoteData.cultivateName + '/' + quoteData.cropName + '/' + sellerName;
            individualQuote.GeneralQuotas__c = quoteData.quoteId;
            individualQuote.Crop__c = quoteData.cropId;
            individualQuote.Seller__c = quoteData.sellerId;
            individualQuote.Cultivate__c = quoteData.cultivateId;
            individualQuote.Quantity__c = quoteData.quantity;
            individualQuote.Consumed__c = quoteData.consumed;
            individualQuote.Balance__c = quoteData.balance;
            
            insert individualQuote;
            return individualQuote.Id;
        } catch (Exception ex) {
            System.debug('Erro: ' + ex.getMessage() + '   -   ' + ex.getStackTraceString());
            return 'Erro: ' + ex.getMessage() + '   -   ' + ex.getStackTraceString();
        }
    }

    public class QuoteData {
        public String  quoteId;
        public String  cropId;
        public String  cropName;
        public String  sellerId;
        public String  cultivateId;
        public String  cultivateName;
        public Decimal balance;
        public Decimal consumed;
        public Decimal quantity;
    }
}