force-app/main/default/objects/GeneralQuotas__c/GeneralQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Geral</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Cotas Gerais</relationshipLabel>
    <relationshipName>GeneralQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Cultivate__c.field-meta.xml
<CustomField>
    <fullName>Cultivate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cotas Gerais</relationshipLabel>
    <relationshipName>GeneralQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GeneralQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Atenção: ao selecionar a quantidade, verifique a unidade de medida clicando no produto para que seja disponibilizado a quantidade correta!</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/IndividualQuotas__c.object-meta.xml
<CustomObject>
    <label>Cota Individual</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotas Individuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IndividualQuotas__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Consumed__c.field-meta.xml
<CustomField>
    <fullName>Consumed__c</fullName>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Cultivate__c.field-meta.xml
<CustomField>
    <fullName>Cultivate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/GeneralQuotas__c.field-meta.xml
<CustomField>
    <fullName>GeneralQuotas__c</fullName>
    <label>Cota Geral (Saldo Macro)</label>
    <referenceTo>GeneralQuotas__c</referenceTo>
    <relationshipLabel>Cotas Individuais</relationshipLabel>
    <relationshipName>IndividualQuotas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IndividualQuotas__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CTV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IndividualQuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ClasseAvaliacao__c.field-meta.xml
<CustomField>
    <fullName>ClasseAvaliacao__c</fullName>
    <label>Classe Avaliação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/GrupoQuimico__c.field-meta.xml
<CustomField>
    <fullName>GrupoQuimico__c</fullName>
    <label>Grupo Químico</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MarcadoEliminacao__c.field-meta.xml
<CustomField>
    <fullName>MarcadoEliminacao__c</fullName>
    <label>Marcado Eliminação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Multiplicity__c.field-meta.xml
<CustomField>
    <fullName>Multiplicity__c</fullName>
    <label>Mulitplicidade</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NCM__c.field-meta.xml
<CustomField>
    <fullName>NCM__c</fullName>
    <label>NCM</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroRegistro__c.field-meta.xml
<CustomField>
    <fullName>NumeroRegistro__c</fullName>
    <externalId>true</externalId>
    <label>Número Registro</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OrigemMaterial__c.field-meta.xml
<CustomField>
    <fullName>OrigemMaterial__c</fullName>
    <label>Origem Material</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrincipleActive__c.field-meta.xml
<CustomField>
    <fullName>PrincipleActive__c</fullName>
    <label>Princípio Ativo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo de Produtos</label>
    <referenceTo>ProductGroup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produtos</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de Medida</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductGroup__c/ProductGroup__c.object-meta.xml
<CustomObject>
    <label>Grupo de Produto</label>
    <nameField>
        <label>Nome do Grupo de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupo de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductGroup__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <label>Hierarquia de Produtos</label>
    <nameField>
        <label>Hierarquia de Produtos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHierarchy__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Código da Hierarquia</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/BillingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BillingStartDate__c</fullName>
    <label>Data Inicio Faturament</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateBilling__c.field-meta.xml
<CustomField>
    <fullName>EndDateBilling__c</fullName>
    <label>Data Fim Faturamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateInsertionOrders__c.field-meta.xml
<CustomField>
    <fullName>EndDateInsertionOrders__c</fullName>
    <label>Data Fim Inserção Pedidos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Safra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/NumberOfDaysAfterPayment__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterPayment__c</fullName>
    <label>Quantidade de Dias Após Pagamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/PaymentBaseDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentBaseDate__c</fullName>
    <label>Data Base Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/ReleaseStatus__c.field-meta.xml
<CustomField>
    <fullName>ReleaseStatus__c</fullName>
    <label>Status Liberação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safra__c/fields/StartDateOrderInsertion__c.field-meta.xml
<CustomField>
    <fullName>StartDateOrderInsertion__c</fullName>
    <label>Data Inicio Inserção Pedidos</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/IndividualQuotasTriggerTest.cls
@isTest
public class IndividualQuotasTriggerTest {
    @testSetup
    public static void makeData() {
        Safra__c crop = new Safra__c(
            Name = 'Safra 01',
            Name__c = 'Safra 1',
            Code__c = '001',
            BillingStartDate__c = System.today(),
            StartDateOrderInsertion__c = System.today(),
            EndDateBilling__c = System.today().addDays(90),
            EndDateInsertionOrders__c = System.today().addDays(90),
            NumberOfDaysAfterPayment__c = System.today().addDays(10),
            PaymentBaseDate__c = System.today().addDays(90),
            ReleaseStatus__c = 'Ativo'
        );
        insert crop;

        ProductHierarchy__c productHierarchy = new ProductHierarchy__c(
            Name = 'Hierarquia',
            External_Id__c = '001'
        );
        insert productHierarchy;

        ProductGroup__c productGroup = new ProductGroup__c(
            Name = 'Grãos',
            ExternalId__c ='001'
        );
        insert productGroup;

        Product2 product = new Product2(
            Name = 'Milho',
            ExternalId__c = '001',
            ProductCode = '001',
            CurrencyIsoCode = 'BRL',
            IsActive = true,
            PrincipleActive__c = 'Salicilina',
            ProductGroup__c = productGroup.Id,
            Multiplicity__c = 5,
            ClasseAvaliacao__c = 'A',
            GrupoQuimico__c = 'A',
            MarcadoEliminacao__c = 'A',
            NCM__c = 'A',
            NumeroRegistro__c = '2',
            OrigemMaterial__c = 'Ferro',
            UnidadeMedida__c = 'Quilos',
            ProductHierarchy__c = productHierarchy.Id
        );
        insert product;

        GeneralQuotas__c generalQuota = new GeneralQuotas__c(
            Quantity__c = 1000,
            Balance__c = 1000,
            Consumed__c = 0,
            Crop__c = crop.Id,
            Cultivate__c = product.Id
        );
        insert generalQuota;
    }

    @isTest
    public static void individualQuotaTest() {
        IndividualQuotas__c individualQuota = new IndividualQuotas__c(
            Quantity__c = 1000,
            Balance__c = 1000,
            Consumed__c = 0,
            Cultivate__c = [SELECT Id FROM Product2 LIMIT 1].Id,
            GeneralQuotas__c = [SELECT Id FROM GeneralQuotas__c LIMIT 1].Id,
            Crop__c = [SELECT Id FROM Safra__c LIMIT 1].Id,
            Seller__c = UserInfo.getUserId()
        );
        insert individualQuota;
        update individualQuota;
    }
}