force-app/main/default/objects/OrgVProduct__c/OrgVProduct__c.object-meta.xml
<CustomObject>
    <label>OrgV do Produto</label>
    <nameField>
        <displayFormat>ORGV-{00000}</displayFormat>
        <label>OrgV do Produto Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrgV do Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgVProduct__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Setor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgVProduct__c/fields/OrgVExternal__c.field-meta.xml
<CustomField>
    <fullName>OrgVExternal__c</fullName>
    <externalId>true</externalId>
    <label>OrgV External</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrgVProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OrgV do Produto</relationshipLabel>
    <relationshipName>OrgV_do_Produto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrgVProduct__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>OrgV do Produto</relationshipLabel>
    <relationshipName>OrgV_do_Produto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrgVProduct__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adicionada</fullName>
            </value>
            <value>
                <fullName>Removida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgVProduct__c/fields/SupplierCenter__c.field-meta.xml
<CustomField>
    <fullName>SupplierCenter__c</fullName>
    <label>Centro Fornecedor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ClasseAvaliacao__c.field-meta.xml
<CustomField>
    <fullName>ClasseAvaliacao__c</fullName>
    <label>Classe Avaliação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/GrupoQuimico__c.field-meta.xml
<CustomField>
    <fullName>GrupoQuimico__c</fullName>
    <label>Grupo Químico</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MarcadoEliminacao__c.field-meta.xml
<CustomField>
    <fullName>MarcadoEliminacao__c</fullName>
    <label>Marcado Eliminação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NCM__c.field-meta.xml
<CustomField>
    <fullName>NCM__c</fullName>
    <label>NCM</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroRegistro__c.field-meta.xml
<CustomField>
    <fullName>NumeroRegistro__c</fullName>
    <externalId>true</externalId>
    <label>Número Registro</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OrigemMaterial__c.field-meta.xml
<CustomField>
    <fullName>OrigemMaterial__c</fullName>
    <label>Origem Material</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo de Produtos</label>
    <referenceTo>ProductGroup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produtos</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductSubgroup__c.field-meta.xml
<CustomField>
    <fullName>ProductSubgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubGrupo de Produtos</label>
    <referenceTo>ProductSubGroup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de Medida</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductGroup__c/ProductGroup__c.object-meta.xml
<CustomObject>
    <label>Grupo de Produto</label>
    <nameField>
        <label>Nome do Grupo de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupo de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductGroup__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <label>Hierarquia de Produtos</label>
    <nameField>
        <label>Hierarquia de Produtos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHierarchy__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Código da Hierarquia</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductSubGroup__c/ProductSubGroup__c.object-meta.xml
<CustomObject>
    <label>SubGrupo de Produtos</label>
    <nameField>
        <label>Nome do SubGrupo de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGrupos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductSubGroup__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationINProductTest.cls
@isTest
public with sharing class IntegrationINProductTest {
    
    @TestSetup
    static void makeData(){
        ProductHierarchy__c productHierarchy = new ProductHierarchy__c(
            Name = 'Hierarquia Teste',
            External_Id__c ='hierarquia01'
        );
        
		insert productHierarchy;
        
        ProductGroup__c productGroup = new ProductGroup__c(
            Name = 'Grupo de produto Teste',
            ExternalId__c = 'gp01'
        );
		insert productGroup;
        
        ProductSubgroup__c productSubGroup = new ProductSubgroup__c( 
            Name =  'SubGrupo de produto Teste',
            ExternalId__c = 'sgp01'
        );
		insert productSubGroup;
        
        SalesOrg__c salesOrg = new SalesOrg__c(
            Name = 'AgroGalaxy',
            SalesOrganizationCode__c = '1000'
        );
        
        insert salesOrg;

        Product2 product = new Product2(
            Name = 'Laptop X200', 
            Family = 'Hardware',
            ExternalId__c = '0001',
            ProductCode__c = '0001',
            ProductCode = '0001',
            ClasseAvaliacao__c = 'av01',
            GrupoQuimico__c = 'bg1',
            MarcadoEliminacao__c = 'tes01',
            NCM__c = '85432000',
            NumeroRegistro__c = '2',
            OrigemMaterial__c = 'sp',
            UnidadeMedida__c = 'un'
        );
        
        insert product;
        
        Product2 product2 = new Product2(
            Id = Product.Id,
            Name = 'Laptop X200', 
            Family = 'Hardware',
            ExternalId__c = '0001',
            ProductCode__c = '0001',
            ProductCode = '0001',
            ClasseAvaliacao__c = 'av01',
            GrupoQuimico__c = 'bg1',
            MarcadoEliminacao__c = 'tes01',
            NCM__c = '85432000',
            NumeroRegistro__c = '2',
            OrigemMaterial__c = 'sp',
            UnidadeMedida__c = 'l'
        );
        update product2;
        
        OrgVProduct__c orgV = new OrgVProduct__c(
        	OrgVExternal__c = '00012',
            SalesOrg__c = salesOrg.Id,
            Product__c = product.Id,
            Department__c = '10',
            SupplierCenter__c = '1013',
            Status__c = 'Adicionada'
        );
        insert orgV;
    }

    @isTest
    static void verifyIntegrationProduct(){
        List<TemplateDataIntegrationFields.Product2INData> listProductList = new List<TemplateDataIntegrationFields.Product2INData>(); //Lista
        TemplateDataIntegrationFields.Product2INData lisProduct = new TemplateDataIntegrationFields.Product2INData(); //Objeto
        lisProduct.TextoBreveMaterial = 'Produto Agro';
        lisProduct.ProductCode = '100';
        lisProduct.DescricaoMaterial = 'Semente Agro';
        lisProduct.UnidadeMedida = 'Kg';
        lisProduct.UnidadeMedidaRemessa = 'Kg';
        lisProduct.TipoMaterial = 'Semente';
        lisProduct.hierarquiaProduto = 'hierarquia01';//Lookup
        lisProduct.GrupoMercadoria = 'gp01';//Lookup
        lisProduct.SubgrupoMercadoria = 'sgp01';//Lookup
        lisProduct.SubgrupoMercadoria2 = 'PREMIUM';
        lisProduct.MarcadoEliminacao = 'Sem elminação';
        lisProduct.UnidadePeso = 'kg';
        lisProduct.ClasseAvaliacao = 'Top';
        lisProduct.OrigemMaterial = 'Minas';
        lisProduct.Marca = 'semente storm';
        lisProduct.NCM = '85432000';
        lisProduct.GrupoQuimico = 'sem';
        lisProduct.IngredienteAtivo = 'terra';
        lisProduct.NumeroRegistro = '0405';
        lisProduct.PesoBruto = 10;
        lisProduct.multiplicidade = 1;
        
        TemplateDataIntegrationFields.OrgVProductINData listOrgVProduct = new TemplateDataIntegrationFields.OrgVProductINData();
        listOrgVProduct.OrganizacaoVendas = '1000'; //Lookup
        listOrgVProduct.OrgProduct = '100'; //Lookup
        listOrgVProduct.SetorAtividade = '10';
        listOrgVProduct.centroFilial = '1000';
        listOrgVProduct.Status = 'Adicionada';
        lisProduct.orgVProductItems = new List<TemplateDataINtegrationFields.OrgVProductINData>();
        lisProduct.orgVProductItems.add(listOrgVProduct);
        listProductList.add(lisProduct);
        IntegrationINProduct.ResponseModel modelo = IntegrationINProduct.upsertProduct(listProductList);
    }
}