force-app/main/default/objects/JurosDescontoAntecipao__c/JurosDescontoAntecipao__c.object-meta.xml
<CustomObject>
    <label>Lista de Preço</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Lista de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listas de Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JurosDescontoAntecipao__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/recordTypes/ZPR0.recordType-meta.xml
<RecordType>
    <fullName>ZPR0</fullName>
    <active>true</active>
    <label>Preço</label>
</RecordType>

force-app/main/default/classes/CancelPriceListController.cls
public without sharing class CancelPriceListController {
    @AuraEnabled
    public static Boolean cancelPriceList(Id recordId) {
        Id priceRecType = Schema.SObjectType.JurosDescontoAntecipao__c.getRecordTypeInfosByDeveloperName().get('ZPR0').getRecordTypeId();
        JurosDescontoAntecipao__c priceList = [SELECT Id, IsActive__c, RecordTypeId FROM JurosDescontoAntecipao__c WHERE Id =: recordId LIMIT 1];
        
        if (priceList.IsActive__c && priceList.RecordTypeId == priceRecType) {
            priceList.IsActive__c = false;
            update priceList;
            return true;
        }
        return false;
    }
}