force-app/main/default/objects/JurosDescontoAntecipao__c/JurosDescontoAntecipao__c.object-meta.xml
<CustomObject>
    <label>Lista de Preço</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Lista de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listas de Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JurosDescontoAntecipao__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/recordTypes/ZPR0.recordType-meta.xml
<RecordType>
    <fullName>ZPR0</fullName>
    <active>true</active>
    <label>Preço</label>
</RecordType>

force-app/main/default/classes/CancelPriceListControllerTest.cls
@isTest
public class CancelPriceListControllerTest {
    @testSetup public static void makeData() {
        JurosDescontoAntecipao__c listPrice = new JurosDescontoAntecipao__c();
        listPrice.RecordTypeId = Schema.SObjectType.JurosDescontoAntecipao__c.getRecordTypeInfosByDeveloperName().get('ZPR0').getRecordTypeId();
        listPrice.IsActive__c = true;
        insert listPrice;
    }

    @isTest public static void cancelPriceListTest() {
        Boolean response = CancelPriceListController.cancelPriceList([SELECT Id FROM JurosDescontoAntecipao__c LIMIT 1].Id);
        System.assert(response);
    }
}