force-app/main/default/objects/BarterTaxes__c/BarterTaxes__c.object-meta.xml
<CustomObject>
    <label>Impostos Barter</label>
    <nameField>
        <displayFormat>IB-{0000}</displayFormat>
        <label>Impostos Barter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos Barter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BarterTaxes__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Imposto Barter</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/CustomerTaxes__c.object-meta.xml
<CustomObject>
    <label>Impostos do Cliente</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Impostos do Cliente Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos dos Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerTaxes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Impostos dos Clientes</relationshipLabel>
    <relationshipName>Impostos_dos_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Imposto Cliente</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Organizacao de Venda</relationshipLabel>
    <relationshipName>Organizacao_de_Venda</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imposto</label>
    <referenceTo>BarterTaxes__c</referenceTo>
    <relationshipLabel>Impostos dos Clientes</relationshipLabel>
    <relationshipName>Impostos_dos_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerTaxesHelper.cls
public with sharing class CustomerTaxesHelper {
    private static Boolean isEnabled;

    static{
        isEnabled = true;
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }

    public static void setExternalId(List<CustomerTaxes__c> customerTaxesList){
        for(CustomerTaxes__c customerTaxes : customerTaxesList){
            String impostBarter;
            String salesOrg;
            if(customerTaxes.Tax__c != null) impostBarter = customerTaxes.Tax__r.ExternalId__c;
            if(customerTaxes.SalesOrg__c != null) salesOrg = customerTaxes.SalesOrg__r.SalesOrganizationCode__c;
            customerTaxes.ExternalId__c = customerTaxes.Account__r.ExternalId__c + '-' + impostBarter + '-' + salesOrg + '-' + customerTaxes.Name__c;
        }
    }
}