force-app/main/default/objects/Cadastro_ClientedaVisita__c/Cadastro_ClientedaVisita__c.object-meta.xml
<CustomObject>
    <label>Cadastro de Cliente da Visita</label>
    <nameField>
        <label>Nome do Cadastro de Clientes da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cadastros de Clientes da Visita</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cadastros de Clientes da Visita</relationshipLabel>
    <relationshipName>Cadastros_de_Clientes_da_Visita</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/ChekIn__c.field-meta.xml
<CustomField>
    <fullName>ChekIn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chek-in da Visita</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/DataVisita__c.field-meta.xml
<CustomField>
    <fullName>DataVisita__c</fullName>
    <label>Data/hora da Visita</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/Local_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Local_da_Visita__c</fullName>
    <label>Local da Visita</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/PlanejamentoVisita__c.field-meta.xml
<CustomField>
    <fullName>PlanejamentoVisita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planejamento de Visita</label>
    <referenceTo>VisitPlanning__c</referenceTo>
    <relationshipLabel>Clientes da Visita</relationshipLabel>
    <relationshipName>Cadastros_de_Clientes_da_Visita</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/Status_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Status_da_Visita__c</fullName>
    <label>Status da Visita</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planejada</fullName>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Finalizado Com Pendências</fullName>
            </value>
            <value>
                <fullName>Finalizado e Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cadastro_ClientedaVisita__c/fields/Tipo_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Tipo_da_Visita__c</fullName>
    <label>Tipo da Visita</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecção de Vendas</fullName>
            </value>
            <value>
                <fullName>Serviço Técnico</fullName>
            </value>
            <value>
                <fullName>Coleta de Documentos/Assinaturas</fullName>
            </value>
            <value>
                <fullName>Ações de Relacionamento</fullName>
            </value>
            <value>
                <fullName>Palestras e Treinamentos técnicos</fullName>
            </value>
            <value>
                <fullName>Geração de Demanda</fullName>
            </value>
            <value>
                <fullName>Tour/Dia de Campo</fullName>
            </value>
            <value>
                <fullName>Cobrança</fullName>
            </value>
            <value>
                <fullName>Coleta de Amostras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cultura__c/Cultura__c.object-meta.xml
<CustomObject>
    <label>Cultura</label>
    <nameField>
        <label>Nome de Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Cultura</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cultura__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Cultura</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fotos__c/Fotos__c.object-meta.xml
<CustomObject>
    <label>Foto</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Fotos Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fotos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fotos__c/fields/ClienteVisita__c.field-meta.xml
<CustomField>
    <fullName>ClienteVisita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cadastro de Cliente da Visita</label>
    <referenceTo>Cadastro_ClientedaVisita__c</referenceTo>
    <relationshipLabel>Fotos</relationshipLabel>
    <relationshipName>Fotos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/Observation__c.field-meta.xml
<CustomField>
    <fullName>Observation__c</fullName>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/BillingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BillingStartDate__c</fullName>
    <label>Data Inicio Faturament</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Safra</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateBilling__c.field-meta.xml
<CustomField>
    <fullName>EndDateBilling__c</fullName>
    <label>Data Fim Faturamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateInsertionOrders__c.field-meta.xml
<CustomField>
    <fullName>EndDateInsertionOrders__c</fullName>
    <label>Data Fim Inserção Pedidos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Safra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/NumberOfDaysAfterPayment__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterPayment__c</fullName>
    <label>Quantidade de Dias Após Pagamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/ReleaseStatus__c.field-meta.xml
<CustomField>
    <fullName>ReleaseStatus__c</fullName>
    <label>Status Liberação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safra__c/fields/StartDateOrderInsertion__c.field-meta.xml
<CustomField>
    <fullName>StartDateOrderInsertion__c</fullName>
    <label>Data Inicio Inserção Pedidos</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/VisitPlanning__c.object-meta.xml
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Planejamento da Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamento de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/fields/CTVvisit__c.field-meta.xml
<CustomField>
    <fullName>CTVvisit__c</fullName>
    <label>(Apagar campo)CTV da Visita</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Cultura__c</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data Fim do Plano</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/InitialDate__c.field-meta.xml
<CustomField>
    <fullName>InitialDate__c</fullName>
    <label>Data de Início do Plano</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/SellOrg__c.field-meta.xml
<CustomField>
    <fullName>SellOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitControllerTest.cls
@isTest
public with sharing class VisitControllerTest {
    public VisitControllerTest() {}

    @TestSetup
    static void makeData(){
        //Requisitos: Account, Planejamento de visita
        Account ac = new Account(
            Name = 'Teste 1'
        );
        

        Safra__c s = new Safra__c(
            Code__c = '1223',
            Name = 'Safra Teste',
            Name__c = 'Safra Teste',
            BillingStartDate__c = System.today(),
            EndDateBilling__c = System.today(),
            EndDateInsertionOrders__c = System.today(),
            NumberOfDaysAfterPayment__c = System.today(),
            ReleaseStatus__c = 'Ativo',
            StartDateOrderInsertion__c = System.today()

        );

        Cultura__c cultura = new Cultura__c(
            Name = 'Safrinha',
            Name__c = 'Safrinha',
            Codigo__c = '1234'
        );

        insert ac;
        insert s;
        insert cultura;

        SalesOrg__c so = new SalesOrg__c(
            Name = 'AgroGalaxy'
        );

        insert so;
        List<Cultura__c> clist = [SELECT Id FROM Cultura__c LIMIT 1];
        List<Safra__c> sList = [SELECT Id FROM Safra__c LIMIT 1];
        List<SalesOrg__c> salesList = [SELECT Id FROM SalesOrg__c LIMIT 1];
        VisitPlanning__c vp = new VisitPlanning__c(
            CTVvisit__c = 'Teste',
            Culture__c = clist.get(0).Id,
            EndDate__c = System.today(),
            InitialDate__c = System.today(),
            Safra__c = sList.get(0).Id,
            SellOrg__c = salesList.get(0).Id
        );
        insert vp;

        List<Account> accList = [SELECT Id FROM ACCOUNT LIMIT 1];
        List<VisitPlanning__c> vpList = [SELECT Id FROM VisitPlanning__c LIMIT 1];
        Cadastro_ClientedaVisita__c ccv = new Cadastro_ClientedaVisita__c(
            Account__c = accList.get(0).Id,
            ChekIn__c = true,
            DataVisita__c = Datetime.now(),
            Local_da_Visita__c = 'Local teste',
            PlanejamentoVisita__c = vpList.get(0).Id,
            Status_da_Visita__c = 'Planejada',
            Tipo_da_Visita__c = 'Serviço Técnico'
        );

        insert ccv;
        List<Cadastro_ClientedaVisita__c> cvList = [SELECT Id FROM Cadastro_ClientedaVisita__c LIMIT 1];
        Fotos__c photo = new Fotos__c(
            ClienteVisita__c = cvList.get(0).Id,
            Observation__c = 'Teste'
        );
        insert photo;

        //Requisito para as fotos e Cadastro do Cliente
    }

    @isTest
    public static void verifyDateFormat(){
        String dateTest = VisitController.getDatetime();

        System.assert((String.isNotBlank(dateTest) && String.isNotEmpty(dateTest)), 'Os dados resultaram em falha');
    }

    @isTest
    public static void verifyQueries(){
        List<Cadastro_ClientedaVisita__c> cp = [SELECT Id FROM Cadastro_ClientedaVisita__c LIMIT 1];
        List<Fotos__c> p = [SELECT Id FROM Fotos__c LIMIT 1];
        List<Cadastro_ClientedaVisita__c> responseCadastro = VisitController.getVisitById(Id.valueOf(cp.get(0).Id), new Set<String>{
            'Id', 'Name', 'Local_da_Visita__c', 'Tipo_da_Visita__c' , 'PlanejamentoVisita__r.Culture__r.Name' ,'PlanejamentoVisita__r.Safra__r.Name' , 'PlanejamentoVisita__r.CTVvisit__c', 'PlanejamentoVisita__r.SellOrg__r.Name' , 'Account__r.Name', 'Account__r.BillingStreet', 'Account__r.BillingState' , 'Account__r.Phone', 'Account__r.BillingCity', 'DataVisita__c'
        , 'Account__r.BillingLongitude', 'Account__r.BillingLatitude'
        });
        List<Fotos__c> responseFoto = VisitController.getPhotoByClientId(Id.valueOf(cp.get(0).Id), new Set<String>{
            'Id','Observation__c', 'ClienteVisita__c'
        });
        List<ContentVersion> contentList = VisitController.getFileByPhotoId(p);
        
        System.assert(responseCadastro.size() != 0);
        System.assert(responseFoto.size() != 0);
        System.assert(contentList.size() == 0);

    }

    @isTest 
    public static void verifyConstructor(){
        List<Cadastro_ClientedaVisita__c> cp = [SELECT Id FROM Cadastro_ClientedaVisita__c LIMIT 1];
        List<Cadastro_ClientedaVisita__c> responseCadastro = VisitController.getVisitById(Id.valueOf(cp.get(0).Id), new Set<String>{
            'Id', 'Name', 'Local_da_Visita__c', 'Tipo_da_Visita__c' , 'PlanejamentoVisita__r.Culture__r.Name' ,'PlanejamentoVisita__r.Safra__r.Name' , 'PlanejamentoVisita__r.CTVvisit__c', 'PlanejamentoVisita__r.SellOrg__r.Name' , 'Account__r.Name', 'Account__r.BillingStreet', 'Account__r.BillingState' , 'Account__r.Phone', 'Account__r.BillingCity', 'DataVisita__c'
        , 'Account__r.BillingLongitude', 'Account__r.BillingLatitude'
        });

        VisitController.VisitDAO visitTest = new VisitController.VisitDAO(responseCadastro.get(0));
        System.assert(cp.get(0).Id == visitTest.id);
    }
}