force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting para habilitar e desabilitar integrações</description>
    <label>Integração</label>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Log de Integração</label>
    <nameField>
        <displayFormat>LOG{0000000000}</displayFormat>
        <label>Log de Integração Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de integrações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/fields/ExecutionDate__c.field-meta.xml
<CustomField>
    <fullName>ExecutionDate__c</fullName>
    <label>Data de execução</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Fluxo</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/hasAttachment__c.field-meta.xml
<CustomField>
    <fullName>hasAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tem Anexo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Integration__c.field-meta.xml
<CustomField>
    <fullName>Integration__c</fullName>
    <label>Integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/PayloadIN__c.field-meta.xml
<CustomField>
    <fullName>PayloadIN__c</fullName>
    <label>Payload IN</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/PayloadOUT__c.field-meta.xml
<CustomField>
    <fullName>PayloadOUT__c</fullName>
    <label>Payload OUT</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationLog.cls
public with sharing class IntegrationLog {

    public static Id createLog(String integrationName, String recordTypeName, String payloadIN, String payloadOUT, Boolean hasAnyErrors){
        System.debug('ON WS LOG: '+integrationName);

        Boolean shouldUseAttachmentIN  = (payloadIN.length() > 100000);
        Boolean shouldUseAttachmentOUT = (payloadOUT.length() > 100000);

        Datetime tNow = System.now();
        
        IntegrationLog__c log = new IntegrationLog__c(
            Flow__c      = recordTypeName,
            Integration__c    = integrationName,
            hasAttachment__c = (shouldUseAttachmentIN || shouldUseAttachmentOUT),
            PayloadIN__c     = (shouldUseAttachmentIN  ? '' : payloadIN),
            PayloadOUT__c    = (shouldUseAttachmentOUT ? '' : payloadOUT),
            ExecutionDate__c =  tNow,
            Status__c         = (hasAnyErrors ? 'ERRO' : 'OK')
        );

        try{
            insert log;

            // Maximum Size for a String
            if (shouldUseAttachmentIN){
            	createAttachment(log.Id, integrationName, 'IN', log.Name, String.valueOf(tNow), payloadIN);
            }

            if (shouldUseAttachmentOUT){
            	createAttachment(log.Id, integrationName, 'OUT', log.Name, String.valueOf(tNow), payloadOUT);
            }

            System.debug('NEW LOG CREATED: '+log.Id);
        }catch(Exception e){
            System.debug('EXCEPTION ON LOG - Please review parameters - '+e.getMessage()+' - '+e.getStackTraceString());
        }

        return log.Id;
    }

    @TestVisible
    private static void createAttachment(String recordId, String integrationName, String inOrOut, String logName, String timeAsString, String payload){
    	Attachment att = new Attachment();
    	att.Name = 'LOG-'+integrationName+'-'+inOrOut+'-'+timeAsString+'.txt';
    	att.Body = Blob.valueOf(payload);
    	att.ParentId = recordId;
    	insert att;
    }
}