force-app/main/default/objects/Account/recordTypes/Propriedade.recordType-meta.xml
<RecordType>
    <fullName>Propriedade</fullName>
    <active>true</active>
    <label>Propriedade</label>
    <picklistValues>
        <picklist>Industry</picklist>
        <values>
            <fullName>Agriculture</fullName>
        </values>
        <values>
            <fullName>Apparel</fullName>
        </values>
        <values>
            <fullName>Banking</fullName>
        </values>
        <values>
            <fullName>Biotechnology</fullName>
        </values>
        <values>
            <fullName>Chemicals</fullName>
        </values>
        <values>
            <fullName>Communications</fullName>
        </values>
        <values>
            <fullName>Construction</fullName>
        </values>
        <values>
            <fullName>Consulting</fullName>
        </values>
        <values>
            <fullName>Education</fullName>
        </values>
        <values>
            <fullName>Electronics</fullName>
        </values>
        <values>
            <fullName>Energy</fullName>
        </values>
        <values>
            <fullName>Engineering</fullName>
        </values>
        <values>
            <fullName>Entertainment</fullName>
        </values>
        <values>
            <fullName>Environmental</fullName>
        </values>
        <values>
            <fullName>Finance</fullName>
        </values>
        <values>
            <fullName>Food %26 Beverage</fullName>
        </values>
        <values>
            <fullName>Government</fullName>
        </values>
        <values>
            <fullName>Healthcare</fullName>
        </values>
        <values>
            <fullName>Hospitality</fullName>
        </values>
        <values>
            <fullName>Insurance</fullName>
        </values>
        <values>
            <fullName>Machinery</fullName>
        </values>
        <values>
            <fullName>Manufacturing</fullName>
        </values>
        <values>
            <fullName>Media</fullName>
        </values>
        <values>
            <fullName>Not For Profit</fullName>
        </values>
        <values>
            <fullName>Other</fullName>
        </values>
        <values>
            <fullName>Recreation</fullName>
        </values>
        <values>
            <fullName>Retail</fullName>
        </values>
        <values>
            <fullName>Shipping</fullName>
        </values>
        <values>
            <fullName>Technology</fullName>
        </values>
        <values>
            <fullName>Telecommunications</fullName>
        </values>
        <values>
            <fullName>Transportation</fullName>
        </values>
        <values>
            <fullName>Utilities</fullName>
        </values>
    </picklistValues>
    <picklistValues>
        <picklist>Type</picklist>
        <values>
            <fullName>Analyst</fullName>
        </values>
        <values>
            <fullName>Competitor</fullName>
        </values>
        <values>
            <fullName>Customer</fullName>
        </values>
        <values>
            <fullName>Integrator</fullName>
        </values>
        <values>
            <fullName>Investor</fullName>
        </values>
        <values>
            <fullName>Other</fullName>
        </values>
        <values>
            <fullName>Partner</fullName>
        </values>
        <values>
            <fullName>Press</fullName>
        </values>
        <values>
            <fullName>Prospect</fullName>
        </values>
        <values>
            <fullName>Reseller</fullName>
        </values>
    </picklistValues>
</RecordType>

force-app/main/default/objects/NotaFiscal__c/NotaFiscal__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal</label>
    <nameField>
        <label>Nota Fiscal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotaFiscal__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CodigoSap__c.field-meta.xml
<CustomField>
    <fullName>CodigoSap__c</fullName>
    <externalId>true</externalId>
    <label>Número do Pedido App</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationINInvoice.cls
@RestResource(urlMapping='/upsertInvoice/*')
global with sharing class IntegrationINInvoice {
    public IntegrationINInvoice() {

    }
    @HttpPost
    global static ResponseModel upsertInvoice(List<TemplateDataIntegrationFields.NotaFiscalINData> request) {
        // Guarda a relação da conta com o pedido
        Map<String, Id> lookups = new Map<String, Id>();

        Set<String> accountLookups = new Set<String>();
        Set<String> orderLookups = new Set<String>();
        Set<String> companyLookups = new Set<String>();
        Set<String> receiverLookups = new Set<String>();
        

    
        List<TemplateDataIntegrationFields.ResponseParent> responseList = new List<TemplateDataIntegrationFields.ResponseParent>();
        List<TemplateDataIntegrationFields.ItensNotaFiscalINData> invoiceItensListToUpsert = new List<TemplateDataIntegrationFields.ItensNotaFiscalINData>();
        //List<TemplateDataINtegrationFields.Product2INData> productListToUpsert = new List<TemplateDataINtegrationFields.Product2INData>();
        List<NotaFiscal__c> notaFiscalListToUpsert = new List<NotaFiscal__c>();
        
        
        //Application of business rules
        for (TemplateDataIntegrationFields.NotaFiscalINData invoice : request){
            // Pega a relação da conta com o pedido
            //Getting account parameters to search
            accountLookups.add(invoice.cliente);
            orderLookups.add(invoice.cpfCnpjCliente);
            companyLookups.add(invoice.codigoEmpresa);
            receiverLookups.add(invoice.propriedade);

            if(invoice.itensNotaFiscal != null) {

                for (TemplateDataIntegrationFields.ItensNotaFiscalINData itensNotafiscal : invoice.itensNotaFiscal){
                    itensNotafiscal.nfExternalId = invoice.numeroNotaFiscal;
                }
                invoiceItensListToUpsert.addAll(invoice.itensNotaFiscal);
                System.debug('invoiceItensListToUpsert' + invoiceItensListToUpsert); 
            }
        }
        
        // Pega o Id da conta com base no CNPJ da conta
        //Account search based on CNPJ field sent
        for (Account account : [SELECT Id, ExternalId__c FROM Account WHERE ExternalId__c IN : receiverLookups]) {
            lookups.put('Account' + account.ExternalId__c, account.Id);
        }
        for (Account account : [SELECT Id, ExternalId__c FROM Account WHERE ExternalId__c IN : accountLookups]) {
            lookups.put('Account' + account.ExternalId__c, account.Id);
        }
        for (Order order : [SELECT Id, CodigoSap__c FROM Order WHERE  CodigoSap__c IN : orderLookups]){
            lookups.put('Order' + order.CodigoSap__c, order.Id);
        }

        for (SalesOrg__c salesOrg : [SELECT Id, SalesOrganizationCode__c FROM SalesOrg__c  WHERE  SalesOrganizationCode__c IN : companyLookups]){
            lookups.put('SalesOrg__c' + salesOrg.SalesOrganizationCode__c, salesOrg.Id);
        }
       

        
        //Converting template to object list and validating required fields
        // Valida e adiciona objeto na lista para upsert
        FactoryDataIntegration.convertSObject(new NotaFiscal__c(), 'IN', request, responseList, notaFiscalListToUpsert, lookups);
          
        //Upserting records (Product)
		IntegrationUtils.upsertRecords(
            Database.upsert(notaFiscalListToUpsert, NotaFiscal__c.Name, false), 
            responseList, 
            notaFiscalListToUpsert, 
            NotaFiscal__c.Name
        );
        System.debug('notaFiscalListToUpsert' + notaFiscalListToUpsert);
        //Upserting records (OrderItem)
        // Upsert OrderItem
        
        Map<String, List<TemplateDataIntegrationFields.Response>> invoiceItensResponse = new Map<String, List<TemplateDataIntegrationFields.Response>>();
        if(invoiceItensListToUpsert.size() != 0){
            invoiceItensResponse.putAll(
                IntegrationINInvoiceItens.upsertInvoiceItens(invoiceItensListToUpsert)
            );
        }

        //Associating child object's response with object response
        // Pega todas as respostas dos OrderItem
        for(TemplateDataIntegrationFields.ResponseParent response : responseList){
            response.items = new List<TemplateDataIntegrationFields.Response>();
            if(invoiceItensResponse.size() != 0 && invoiceItensResponse.containsKey(response.idSalesforce)){
                response.items.addAll(invoiceItensResponse.get(response.idSalesforce));
            } 
            else if(invoiceItensResponse.size() != 0 && invoiceItensResponse.containsKey(response.externalCode)){
                response.items.addAll(invoiceItensResponse.get(response.externalCode));
            }
        }

        //Checking integration errors to log
        // Verifica erros de integração para o log
        Boolean hasError = false;

        for(TemplateDataIntegrationFields.ResponseParent responseInvoice : responseList){
            if(responseInvoice.status == false){
                hasError = true;
                break;
            } else {
                for(TemplateDataIntegrationFields.Response response : responseInvoice.items){
                    if(response.status == false){
                        hasError = true;
                        break;
                    }
                }
            }
            
        }
		
        //Creating integration log
        IntegrationLog.createLog('Nota Fiscal - DataLake', 'IN', JSON.serialize(request), JSON.serialize(responseList), hasError);
        
        //Returning response
         // Retorna a resposta Outbound
        ResponseModel modelo = new ResponseModel();
        modelo.response = responseList;
        return modelo;
    }
    // Classe que cria a resposta
    global class ResponseModel {

        List<TemplateDataIntegrationFields.ResponseParent> response;

        public ResponseModel(List<TemplateDataIntegrationFields.ResponseParent> response) {

            this.response = response;
            
        }
        public ResponseModel() {   
            this.response = new List<TemplateDataIntegrationFields.ResponseParent>();         
        }
    }
}