force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/BillingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BillingStartDate__c</fullName>
    <label>Data Inicio Faturament</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateBilling__c.field-meta.xml
<CustomField>
    <fullName>EndDateBilling__c</fullName>
    <label>Data Fim Faturamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateInsertionOrders__c.field-meta.xml
<CustomField>
    <fullName>EndDateInsertionOrders__c</fullName>
    <label>Data Fim Inserção Pedidos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Safra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/NumberOfDaysAfterPayment__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterPayment__c</fullName>
    <label>Quantidade de Dias Após Pagamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/ReleaseStatus__c.field-meta.xml
<CustomField>
    <fullName>ReleaseStatus__c</fullName>
    <label>Status Liberação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safra__c/fields/StartDateOrderInsertion__c.field-meta.xml
<CustomField>
    <fullName>StartDateOrderInsertion__c</fullName>
    <label>Data Inicio Inserção Pedidos</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesCondition__c/SalesCondition__c.object-meta.xml
<CustomObject>
    <label>Condição de Vendas</label>
    <nameField>
        <label>Condição de Vendas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationINCropDelimitationTest.cls
@isTest
public class IntegrationINCropDelimitationTest {
  
    @TestSetup
    static void makeData(){

        Safra__c safra = new Safra__c(
            Code__c = '111',
            Name = 'Safra Teste',
            Name__c = 'Safra Teste',
            BillingStartDate__c = System.today(),
            EndDateBilling__c = System.today(),
            EndDateInsertionOrders__c = System.today(),
            NumberOfDaysAfterPayment__c = System.today(),
            ReleaseStatus__c = 'Ativo',
            StartDateOrderInsertion__c = System.today()

        );
        insert safra;
        SalesOrg__c so = new SalesOrg__c(
            Name = 'SalesOrganization Teste',
            SalesOrganizationCode__c = '333'
        );
        insert so;
        salesCondition__c sales = new salesCondition__c(
            Name = 'SalesCondition Teste',
            ExternalId__c = '222'
        );
        insert sales;

    }
    
    @isTest
    static void verifyIntegrationINCropDelimitation(){
        List<TemplateDataIntegrationFields.DelimitadoresINData> delimitatorsList = new List<TemplateDataIntegrationFields.DelimitadoresINData>();
        TemplateDataIntegrationFields.DelimitadoresINData delimitators = new TemplateDataIntegrationFields.DelimitadoresINData();
        delimitators.SalesOrganization = '333';
        delimitators.Safra = '111';
        delimitators.PriceList = '222';
        delimitators.StartDateOV = Date.valueOf('2022-09-21');
        delimitators.EndDateOV = Date.valueOf('2022-09-21');
        delimitators.StartDateFaturalmente = Date.valueOf('2022-09-21');
        delimitators.EndDateFaturalmente = Date.valueOf('2022-09-21');
        delimitators.BaseDateFinancing = Date.valueOf('2022-09-21');
        delimitators.AfterPaymentDate = Date.valueOf('2022-09-22');
        delimitatorsList.add(delimitators);
        
        Test.startTest();
        IntegrationINCropDelimitation.ResponseModel model = IntegrationINCropDelimitation.upsertCropDelimitation(delimitatorsList);
        Test.stopTest();
        
        System.debug(model);
    }
}