force-app/main/default/objects/OrderItem/fields/CommercialMargin__c.field-meta.xml
<CustomField>
    <fullName>CommercialMargin__c</fullName>
    <label>Margem Comercial</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>Porcentagem Desconto</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <label>Desconto em Valor</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <label>Preço de Lista</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PracticedPrice__c.field-meta.xml
<CustomField>
    <fullName>PracticedPrice__c</fullName>
    <label>Preço Praticado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/UnitMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasure__c</fullName>
    <label>Unidade de Medida</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderItemApprovalController.cls
public without sharing class OrderItemApprovalController {
    public Id recordId {get;set;}
    
    public List<OrderItem> getorderItems() {
        List<OrderItem> orderItems = [
            SELECT Id,
                   Product2.Name,
                   Quantity,
                   UnitMeasure__c,
                   PracticedPrice__c,
                   ListPrice__c,
                   DiscountValue__c,
                   DiscountPercent__c,
                   CommercialMargin__c
              FROM OrderItem
             WHERE Id =: recordId
        ];
        return orderItems;
    }
}