force-app/main/default/objects/Account/fields/BpType__c.field-meta.xml
<CustomField>
    <fullName>BpType__c</fullName>
    <label>Tipo de BP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proprietário</fullName>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Propriedade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Propriedade.recordType-meta.xml
<RecordType>
    <fullName>Propriedade</fullName>
    <active>true</active>
    <label>Propriedade</label>
    <picklistValues>
        <picklist>Industry</picklist>
        <values>
            <fullName>Agriculture</fullName>
        </values>
        <values>
            <fullName>Apparel</fullName>
        </values>
        <values>
            <fullName>Banking</fullName>
        </values>
        <values>
            <fullName>Biotechnology</fullName>
        </values>
        <values>
            <fullName>Chemicals</fullName>
        </values>
        <values>
            <fullName>Communications</fullName>
        </values>
        <values>
            <fullName>Construction</fullName>
        </values>
        <values>
            <fullName>Consulting</fullName>
        </values>
        <values>
            <fullName>Education</fullName>
        </values>
        <values>
            <fullName>Electronics</fullName>
        </values>
        <values>
            <fullName>Energy</fullName>
        </values>
        <values>
            <fullName>Engineering</fullName>
        </values>
        <values>
            <fullName>Entertainment</fullName>
        </values>
        <values>
            <fullName>Environmental</fullName>
        </values>
        <values>
            <fullName>Finance</fullName>
        </values>
        <values>
            <fullName>Food %26 Beverage</fullName>
        </values>
        <values>
            <fullName>Government</fullName>
        </values>
        <values>
            <fullName>Healthcare</fullName>
        </values>
        <values>
            <fullName>Hospitality</fullName>
        </values>
        <values>
            <fullName>Insurance</fullName>
        </values>
        <values>
            <fullName>Machinery</fullName>
        </values>
        <values>
            <fullName>Manufacturing</fullName>
        </values>
        <values>
            <fullName>Media</fullName>
        </values>
        <values>
            <fullName>Not For Profit</fullName>
        </values>
        <values>
            <fullName>Other</fullName>
        </values>
        <values>
            <fullName>Recreation</fullName>
        </values>
        <values>
            <fullName>Retail</fullName>
        </values>
        <values>
            <fullName>Shipping</fullName>
        </values>
        <values>
            <fullName>Technology</fullName>
        </values>
        <values>
            <fullName>Telecommunications</fullName>
        </values>
        <values>
            <fullName>Transportation</fullName>
        </values>
        <values>
            <fullName>Utilities</fullName>
        </values>
    </picklistValues>
    <picklistValues>
        <picklist>Type</picklist>
        <values>
            <fullName>Analyst</fullName>
        </values>
        <values>
            <fullName>Competitor</fullName>
        </values>
        <values>
            <fullName>Customer</fullName>
        </values>
        <values>
            <fullName>Integrator</fullName>
        </values>
        <values>
            <fullName>Investor</fullName>
        </values>
        <values>
            <fullName>Other</fullName>
        </values>
        <values>
            <fullName>Partner</fullName>
        </values>
        <values>
            <fullName>Press</fullName>
        </values>
        <values>
            <fullName>Prospect</fullName>
        </values>
        <values>
            <fullName>Reseller</fullName>
        </values>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Removida</fullName>
            </value>
            <value>
                <fullName>Adicionada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cultura__c/Cultura__c.object-meta.xml
<CustomObject>
    <label>Cultura</label>
    <nameField>
        <label>Nome de Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Cultura</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cultura__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Cultura</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/BillingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BillingStartDate__c</fullName>
    <label>Data Inicio Faturament</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Safra</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateBilling__c.field-meta.xml
<CustomField>
    <fullName>EndDateBilling__c</fullName>
    <label>Data Fim Faturamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateInsertionOrders__c.field-meta.xml
<CustomField>
    <fullName>EndDateInsertionOrders__c</fullName>
    <label>Data Fim Inserção Pedidos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Safra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/NumberOfDaysAfterPayment__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterPayment__c</fullName>
    <label>Quantidade de Dias Após Pagamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/ReleaseStatus__c.field-meta.xml
<CustomField>
    <fullName>ReleaseStatus__c</fullName>
    <label>Status Liberação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safra__c/fields/StartDateOrderInsertion__c.field-meta.xml
<CustomField>
    <fullName>StartDateOrderInsertion__c</fullName>
    <label>Data Inicio Inserção Pedidos</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/TechnicalReport__c.object-meta.xml
<CustomObject>
    <description>RTR</description>
    <label>Relatório Técnico</label>
    <nameField>
        <displayFormat>RTR-{0000}</displayFormat>
        <label>Relatório Técnico Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relatórios Técnicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalReport__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Horário da Finalização</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerado</fullName>
                <default>true</default>
                <label>Gerado</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/VisitPlanning__c.field-meta.xml
<CustomField>
    <fullName>VisitPlanning__c</fullName>
    <label>Visita</label>
    <referenceTo>VisitPlanning__c</referenceTo>
    <relationshipLabel>Relatórios Técnicos</relationshipLabel>
    <relationshipName>Relatorios_Tecnicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoSap__c.field-meta.xml
<CustomField>
    <fullName>CodigoSap__c</fullName>
    <externalId>true</externalId>
    <label>Código Sap</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/VisitPlanning__c.object-meta.xml
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Planejamento da Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamento de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/fields/BP_Property__c.field-meta.xml
<CustomField>
    <fullName>BP_Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BP Propriedade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.BpType__c</field>
            <operation>equals</operation>
            <value>Propriedade</value>
        </filterItems>
        <filterItems>
            <field>$Source.Main_BP__c</field>
            <operation>equals</operation>
            <valueField>Account.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planejamento de Visitas (BP Propriedade)</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/CTVvisit__c.field-meta.xml
<CustomField>
    <fullName>CTVvisit__c</fullName>
    <label>(Apagar campo)CTV da Visita</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Horário Final</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <displayFormat>{000000000}</displayFormat>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/MainBP__c.field-meta.xml
<CustomField>
    <fullName>MainBP__c</fullName>
    <label>BP Principal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.BpType__c</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Geração de demanda</fullName>
            </value>
            <value>
                <fullName>Acompanhamento técnico</fullName>
            </value>
            <value>
                <fullName>Acompanhamento colheita</fullName>
            </value>
            <value>
                <fullName>Cobrança</fullName>
            </value>
            <value>
                <fullName>Coleta de Documentos</fullName>
            </value>
            <value>
                <fullName>Coleta assinatura doctos</fullName>
            </value>
            <value>
                <fullName>Fechamento e Planej. de Safra</fullName>
            </value>
            <value>
                <fullName>Evento</fullName>
            </value>
            <value>
                <fullName>Treinamento e Reunião</fullName>
            </value>
            <value>
                <fullName>Ocorrência</fullName>
            </value>
            <value>
                <fullName>Entrega de Produto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Horário Inicial</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agendado</fullName>
                <default>true</default>
                <label>Agendado</label>
            </value>
            <value>
                <fullName>Reagendado</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
            <value>
                <fullName>Atrasado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/VisitSeller__c.field-meta.xml
<CustomField>
    <fullName>VisitSeller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CTV da Visita</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CalloutVisitsTest.cls
@isTest
    public class CalloutVisitsTest {
      
        @TestSetup
        static void makeData(){
    
            Safra__c safra = new Safra__c(
                Code__c = '111',
                Name = 'Safra Teste',
                Name__c = 'Safra Teste',
                BillingStartDate__c = System.today(),
                EndDateBilling__c = System.today(),
                EndDateInsertionOrders__c = System.today(),
                NumberOfDaysAfterPayment__c = System.today(),
                ReleaseStatus__c = 'Ativo',
                StartDateOrderInsertion__c = System.today()
    
            );
            insert safra;
    
            Account account = new Account(
                Name = 'Teste 1',
                BillingStreet = ' ',
                BillingState = '' ,
         
                Phone= '', 
                BpType__c = 'Proprietario',
                BillingCity = ' ', 
                BillingLongitude = 000000,
                BillingLatitude = 00000,
                BillingPostalCode = '',
                ExternalId__c = '11111',
                Company__c = 'Empresa 1'
            );
            insert account;
            Account account2 = new Account(
                Name = 'Teste 2',
                BillingStreet = ' ',
                BillingState = '' ,
                ParentId = account.Id,
                Phone= '', 
                BillingCity = ' ', 
                BpType__c = 'Propriedade',
                BillingLongitude = 000000,
                BillingLatitude = 00000,
                BillingPostalCode = '',
                ExternalId__c = '2222',
                Company__c = 'Empresa 1'
            );
            insert account2;


            Cultura__c cultura = new Cultura__c(
                Name = 'Safrinha',
                Name__c = 'Safrinha',
                Codigo__c = '1234'
            );
            insert cultura;

            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User u = new User(
                Alias = 'standt', Email='standarduser@testorg.com', CodigoSap__c = '010',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='testes_BP_TEST@testes.com');
            insert u;

            SalesOrg__c so = new SalesOrg__c(
                Name = 'AgroGalaxy',
                SalesOrganizationCode__c = '1111'
            );
            insert so;

            VisitPlanning__c vp = new VisitPlanning__c(
                Name = 'test Visit',
                ExternalId__c = 'test123',
                MainBP__c = account.Id,
                BP_Property__c = account2.Id,
                CTVvisit__c = 'Teste',
                VisitSeller__c = u.Id,
                Status__c = 'Agendado',
                Objetivo__c = 'Evento',
                EndTime__c  = Time.newInstance(1, 2, 3, 6),  
			    StartTime__c = Time.newInstance(1, 2, 3, 1),
                Culture__c = cultura.Id,
                EndDate__c = System.today(),
                InitialDate__c = System.today(),
                Safra__c = safra.id,
                SellOrg__c = so.Id
            );
            insert vp;
            TechnicalReport__c technicalReport = new TechnicalReport__c(
                EndDate__c  = System.today(),
                EndTime__c = Time.newInstance(1, 2, 3, 1),
                CancellationReason__c = '',
                Note__c = 'test',
                Status__c = 'Gerado',
                VisitPlanning__c = vp.Id
            );
            insert technicalReport;
            
        }
        
        @isTest
        static void verifyIntegrationOUTVisit(){
            List<VisitPlanning__c> visitList = new List<VisitPlanning__c>([SELECT Id,Name, MainBP__r.ExternalId__c, BP_Property__r.ExternalId__c, InitialDate__c, EndDate__c, StartTime__c, EndTime__c, 
            Status__c, Objetivo__c, Safra__r.Code__c, Culture__r.Codigo__c, Email__c, Presential__c, Reminder__c, Displacement__c, VisitSeller__r.CodigoSap__c, Note__c, ReschedulingReason__c, 
            CancellationReason__c, ExternalId__c FROM VisitPlanning__c LIMIT 1]);
            List<String> visitIdList = new List<String>();
            for(VisitPlanning__c visit : visitList){
                visitIdList.add(visit.Id);
            }
            Test.startTest();
            CalloutVisits.callIntegration(visitIdList);
            Test.stopTest();
            
        }
    }