force-app/main/default/objects/Account/fields/BpType__c.field-meta.xml
<CustomField>
    <fullName>BpType__c</fullName>
    <label>Tipo de BP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proprietário</fullName>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Propriedade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/CustomerTaxes__c.object-meta.xml
<CustomObject>
    <label>Impostos do Cliente</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Impostos do Cliente Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos dos Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerTaxes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Impostos dos Clientes</relationshipLabel>
    <relationshipName>Impostos_dos_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Imposto Cliente</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerTaxes__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Organizacao de Venda</relationshipLabel>
    <relationshipName>Organizacao_de_Venda</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerTaxesHelperTest.cls
@isTest
    public with sharing class CustomerTaxesHelperTest {
        
        @TestSetup
        static void makeData(){
            
    
            SalesOrg__c salesOrg = new SalesOrg__c(
            Name = 'AgroGalaxy',
            SalesOrganizationCode__c = '1111'
            );
            insert salesOrg;
            Account account = new Account(
                Name = 'Teste 1',
                BillingStreet = ' ',
                BillingState = '' ,
                Phone= '', 
                BpType__c = 'Proprietario',
                BillingCity = ' ', 
                BillingLongitude = 000000,
                BillingLatitude = 00000,
                BillingPostalCode = '',
                ExternalId__c = '11111',
                Company__c = 'Empresa 1'
            );
            insert account;
            CustomerTaxes__c customerTax = new CustomerTaxes__c(
                Account__c = account.Id,
                SalesOrg__c = salesOrg.Id,
                Name__c = 'test'
            );
            insert customerTax;
        }

        @isTest
        public 	static void createsExternalIdSucess(){
            Account account = [SELECT Id FROM Account LIMIT 1];
            SalesOrg__c salesOrg = [SELECT Id FROM SalesOrg__c LIMIT 1];
            List<CustomerTaxes__c> customerList = new List<CustomerTaxes__c>();
            CustomerTaxes__c customerTax = new CustomerTaxes__c(
                Account__c = account.Id,
                SalesOrg__c = salesOrg.Id,
                Name__c = 'test1'
            );
            customerList.add(customerTax);
            Test.startTest();
                upsert customerList;
            Test.stopTest();
        }
        @isTest
        public 	static void createsExternalIdError(){
            Account account = [SELECT Id FROM Account LIMIT 1];
            SalesOrg__c salesOrg = [SELECT Id FROM SalesOrg__c LIMIT 1];
            List<CustomerTaxes__c> customerList = new List<CustomerTaxes__c>();
            CustomerTaxes__c customerTax = new CustomerTaxes__c(
                Account__c = account.Id,
                SalesOrg__c = salesOrg.Id,
                Name__c = 'test'
            );
            customerList.add(customerTax);
            Test.startTest();
                insert customerList;
            Test.stopTest();
        }
    }