force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/StateRegistration__c.field-meta.xml
<CustomField>
    <fullName>StateRegistration__c</fullName>
    <label>Inscrição Estadual</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CodigoSap__c.field-meta.xml
<CustomField>
    <fullName>CodigoSap__c</fullName>
    <externalId>true</externalId>
    <label>Número do Pedido App</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Cultura__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDate__c</fullName>
    <label>Data de Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentForm__c.field-meta.xml
<CustomField>
    <fullName>PaymentForm__c</fullName>
    <label>Forma de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Cessão Crédito</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Boleto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Operação Barter</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dinheiro/Adiantamento</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Encontro de Contas</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>Cheque Recebido</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>DOC</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Operação CRA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>TED</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>DOC/TED</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Transferência</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>PIX</label>
            </value>
            <value>
                <fullName>Bonificação</fullName>
                <isActive>false</isActive>
                <label>Bonificação</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente Entrega</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/UnitMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasure__c</fullName>
    <label>Unidade de Medida</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderPageController.cls
public with sharing class OrderPageController {
    public OrderDAO orderToPage {get; set;}
  
    public OrderPageController(){}
    public OrderPageController(ApexPages.StandardController stdController) {
        try
        {
            Id OrderIdPageReference = Id.valueOf(String.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('Id').escapeHtml4()));
            if(OrderIdPageReference != null) generatePDF(OrderIdPageReference);
        }
        catch(Exception e){
            System.debug('Sem ID encontrado');
        }
    }

    public OrderDAO generatePDF(Id orderId){
        Order order = getOrderById(orderId);
        List<OrderItem> orderItemList = getOrderItemByOrderId(orderId);

        this.orderToPage = new OrderDAO(order);

        for(OrderItem orderItem : orderItemList){
            this.orderToPage.orderItemList.add(new OrderItemDAO(orderItem, this.orderToPage.culture));
        }

       
        String downloadingFileName = 'Pedido de Venda-' + this.orderToPage.codeSap + '.pdf';
        Apexpages.currentPage().getHeaders().put( 'content-disposition', 'inline; filename=' + downloadingFileName );
       
        return this.orderToPage;

    }

    public static Order getOrderById(Id orderId){
  
        Set<String> fieldSet = new Set<String>{
            'Id', 'Account.ExternalId__c', 'Account.Name', 'Account.BillingStreet',
            'ShippingAccount__r.Name','Account.BillingCity', 'Account.StateRegistration__c',
            'Account.CPF__c', 'Account.CNPJ__c', 'TotalAmount', 'Description',
            'Account.BillingPostalCode', 'Crop__r.Name', 'PaymentForm__c', 'PaymentDate__c',
            'Currency__c', 'Culture__c', 'CodigoSap__c'
        };

        String query = new Q(Order.SObjectType)
                            .selectFields(fieldSet)
                            .add(Q.condition('Id').equalsTo(orderId))
                            .addLimit(1).build();

        return Database.query(query);
    }

    public static List<OrderItem> getOrderItemByOrderId(Id orderId){

        Set<String> fieldSet = new Set<String>{
            'Product2Id', 'Description', 'UnitMeasure__c', 
            'UnitPrice','Quantity','TotalPrice'
        };

        String query = new Q(OrderItem.SObjectType)
                            .selectFields(fieldSet)
                            .add(Q.condition('OrderId').equalsTo(orderId)).build();

        return Database.query(query);
    }

    public static String getDatetime(){

        Datetime  dt = DateTime.now();
        String dateFormat = dt.format('dd/MM/yyyy', 
        'America/Sao_Paulo');

        return dateFormat;
    }

    public class OrderDAO{
        //Cód. Pessoa, Pessoa, Local, Fazenda, municipio, CPF/CNPJ, I.E., CEP
        //safra, Cond. de Pagamento, Vencimento
        public String codeSap {get; set;}
        public String codeSapOrder {get; set;}
        public String account {get; set;}
        public String accountAddress {get; set;}
        public String ranch {get; set;}
        public String district {get; set;}
        public String CPF_CNPJ {get; set;}
        public String IE {get; set;}
        public String CEP{get; set;}
        public String safra {get; set;}
        public String paymentCondition {get; set;}
        public String dueDate {get; set;}
        public String currencyOrder {get; set;}
        public String culture {get; set;}
        public String totalAmount {get; set;}
        public String observation {get; set;}
        public List<OrderItemDAO> orderItemList {get; set;}

        public OrderDAO(Order order){
            this.codeSap = order.Account.ExternalId__c;
            this.codeSapOrder = order.CodigoSap__c;
            this.account = order.Account.Name;
            this.accountAddress = order.Account.BillingStreet;
            this.ranch = order.ShippingAccount__r.Name;
            this.district = order.Account.BillingCity;
            this.IE = order.Account.StateRegistration__c;
            this.CEP = order.Account.BillingPostalCode;
            this.CPF_CNPJ = order.Account.CNPJ__c == null ? order.Account.CPF__c : order.Account.CNPJ__c;
            this.safra = order.Crop__r.Name;
            this.paymentCondition = order.PaymentForm__c;
            this.currencyOrder = order.Currency__c;
            this.culture = order.Culture__c;
            this.dueDate = String.valueOf(order.PaymentDate__c);
            this.totalAmount = String.valueOf(order.TotalAmount);
            this.observation = order.Description;
            this.orderItemList = new List<OrderItemDAO>();
        }
    }

    public class OrderItemDAO{
        // Cód. Produto Descrição Cultura Unid. Medida Quant. Preço Unit. Valor Total
        public String productCode {get; set;}
        public String description {get; set;}
        public String culture {get;set;}
        public String unitOfMeasure {get; set;}
        public Decimal unitPrice {get; set;}
        public Decimal quantity {get; set;}
        public Decimal totalAmount {get; set;}

        public OrderItemDAO(OrderItem orderItem, String culture){
            this.productCode = orderItem.Product2Id;
            this.description = orderItem.Description;
            this.unitOfMeasure = orderItem.UnitMeasure__c;
            this.unitPrice = orderItem.UnitPrice;
            this.quantity = orderItem.Quantity;
            this.totalAmount = orderItem.TotalPrice;
            this.culture = culture;
        }
    }
}