force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountTest.cls
@isTest
    public with sharing class AccountTest {

        @TestSetup
        static void makeData(){
    
            Account account = new Account(
                Name = 'Teste 1',
                BillingStreet = ' ',
                BillingState = '' ,
                Phone= '', 
                BillingCity = ' ', 
                BillingLongitude = 000000,
                BillingLatitude = 00000,
                BillingPostalCode = '',
                ExternalId__c = '288',
                Company__c = 'Empresa 01'
            );
            insert account;
            
        }
        @isTest 
        static void accountUpdateIntegrationTest(){
            Account account = [SELECT Id, Company__c FROM Account WHERE Name = 'Teste 1' LIMIT 1];
            account.Company__c = 'Empresa Nova';
            Test.startTest();
            update account;
            Test.stopTest();
        }

        @isTest 
        static void accountInserAndDeleteIntegrationTest(){
            Account account = new Account(
            Name = 'Teste 2',
            BillingStreet = ' ',
            BillingState = '' ,
            Phone= '', 
            BillingCity = ' ', 
            BillingLongitude = 000000,
            BillingLatitude = 00000,
            BillingPostalCode = '',
            ExternalId__c = '11111',
            Company__c = 'Empresa 01'
            );  
            insert account;
            Test.startTest();
            
            delete account;
            Test.stopTest();
        }
    }