force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletos__c/Boletos__c.object-meta.xml
<CustomObject>
    <label>Boleto</label>
    <nameField>
        <label>Nome de Boleto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletos__c/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Código do Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Boletos</relationshipLabel>
    <relationshipName>Boletos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Empresa</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Data de Vencimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <label>Data de Emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Boletos</relationshipLabel>
    <relationshipName>Boletos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/WritableLine__c.field-meta.xml
<CustomField>
    <fullName>WritableLine__c</fullName>
    <externalId>true</externalId>
    <label>Linha Digitável</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationINBoletosTest.cls
@isTest
public with sharing class IntegrationINBoletosTest {

    @TestSetup
    static void makeData(){

        Boletos__c boletos = new Boletos__c(
            AccountCode__c ='020',
            ExpirationDate__c = Date.valueOf('2022-09-21'),
            IssueDate__c = Date.valueOf('2022-09-21'),
            SalesOrg__c = '102',
            Value__c = 20.00,
            WritableLine__c = '002'
        );
        insert boletos;

        Account account = new Account(
            Name = 'Testinho11',
            BillingStreet = '',
            BillingState = '' ,
            Phone= '0000011111', 
            BillingCity = ' ', 
            BillingLongitude = 01010101,
            BillingLatitude = 001100,
            BillingPostalCode = '',
            ExternalId__c = '2884',
            Company__c = 'Empresa 012'
        );
        insert account;

        SalesOrg__c salesOrg = new SalesOrg__c(
            Name = 'AgroGalaxy',
            SalesOrganizationCode__c = '2222'
        );
        insert salesOrg;

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testes@testes.com');

        insert u;
        
    }
    @isTest
    static void verifyIntegrationBoletos(){
        List<TemplateDataIntegrationFields.BoletosINData> listBoletosList = new List<TemplateDataIntegrationFields.BoletosINData>();
        TemplateDataIntegrationFields.BoletosINData listBoletos = new TemplateDataIntegrationFields.BoletosINData();
        listBoletos.codigoParceiro = '020';
        listBoletos.vencimentoBoleto = Date.valueOf('2022-09-21');
        listBoletos.dataBoleto = Date.valueOf('2022-09-13');
        listBoletos.empresa = '102';
        listBoletos.valorBoleto = 20.00;
        listBoletos.linhaDigitavel = '002';
        listBoletosList.add(listBoletos);

        IntegrationINBoletos.ResponseModel modelo = IntegrationINBoletos.upsertBoletos(listBoletosList);
        //IntegrationINOrderAppdigital.ResponseModel toPass = new IntegrationINOrderAppdigital.ResponseModel(modelo.response);
        System.debug(modelo);
    }
}