force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Propriedade.recordType-meta.xml
<RecordType>
    <fullName>Propriedade</fullName>
    <active>true</active>
    <label>Propriedade</label>
    <picklistValues>
        <picklist>Industry</picklist>
        <values>
            <fullName>Agriculture</fullName>
        </values>
        <values>
            <fullName>Apparel</fullName>
        </values>
        <values>
            <fullName>Banking</fullName>
        </values>
        <values>
            <fullName>Biotechnology</fullName>
        </values>
        <values>
            <fullName>Chemicals</fullName>
        </values>
        <values>
            <fullName>Communications</fullName>
        </values>
        <values>
            <fullName>Construction</fullName>
        </values>
        <values>
            <fullName>Consulting</fullName>
        </values>
        <values>
            <fullName>Education</fullName>
        </values>
        <values>
            <fullName>Electronics</fullName>
        </values>
        <values>
            <fullName>Energy</fullName>
        </values>
        <values>
            <fullName>Engineering</fullName>
        </values>
        <values>
            <fullName>Entertainment</fullName>
        </values>
        <values>
            <fullName>Environmental</fullName>
        </values>
        <values>
            <fullName>Finance</fullName>
        </values>
        <values>
            <fullName>Food %26 Beverage</fullName>
        </values>
        <values>
            <fullName>Government</fullName>
        </values>
        <values>
            <fullName>Healthcare</fullName>
        </values>
        <values>
            <fullName>Hospitality</fullName>
        </values>
        <values>
            <fullName>Insurance</fullName>
        </values>
        <values>
            <fullName>Machinery</fullName>
        </values>
        <values>
            <fullName>Manufacturing</fullName>
        </values>
        <values>
            <fullName>Media</fullName>
        </values>
        <values>
            <fullName>Not For Profit</fullName>
        </values>
        <values>
            <fullName>Other</fullName>
        </values>
        <values>
            <fullName>Recreation</fullName>
        </values>
        <values>
            <fullName>Retail</fullName>
        </values>
        <values>
            <fullName>Shipping</fullName>
        </values>
        <values>
            <fullName>Technology</fullName>
        </values>
        <values>
            <fullName>Telecommunications</fullName>
        </values>
        <values>
            <fullName>Transportation</fullName>
        </values>
        <values>
            <fullName>Utilities</fullName>
        </values>
    </picklistValues>
    <picklistValues>
        <picklist>Type</picklist>
        <values>
            <fullName>Analyst</fullName>
        </values>
        <values>
            <fullName>Competitor</fullName>
        </values>
        <values>
            <fullName>Customer</fullName>
        </values>
        <values>
            <fullName>Integrator</fullName>
        </values>
        <values>
            <fullName>Investor</fullName>
        </values>
        <values>
            <fullName>Other</fullName>
        </values>
        <values>
            <fullName>Partner</fullName>
        </values>
        <values>
            <fullName>Press</fullName>
        </values>
        <values>
            <fullName>Prospect</fullName>
        </values>
        <values>
            <fullName>Reseller</fullName>
        </values>
    </picklistValues>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IntegrationINInvoiceTest.cls
@isTest
public with sharing class IntegrationINInvoiceTest {
  
    @TestSetup
    static void makeData(){
        Account account = new Account (
            Name = 'Teste 12',
            BillingStreet = ' ',
            BillingState = '' ,
            Phone= '00000000000', 
            BillingCity = ' ', 
            BillingLongitude = 000000,
            BillingLatitude = 00000,
            BillingPostalCode = '',
            ExternalId__c = '2884',
            Company__c = 'Empresa 012'
        );
        insert account;

        Account account2 = new Account (
            Name = 'Propriedade',
            BillingStreet = ' ',
            BillingState = '' ,
            Phone= '00000000000', 
            BillingCity = ' ', 
            BillingLongitude = 000000,
            BillingLatitude = 00000,
            BillingPostalCode = '',
            ExternalId__c = '2885',
            Company__c = 'Propriedade 012'
        );
        insert account2;
        
    }
    @isTest
    static void verifyIntegrationInvoice(){
        List<TemplateDataINtegrationFields.ItensNotaFiscalINData> listItemsList = new List<TemplateDataINtegrationFields.ItensNotaFiscalINData>();
        TemplateDataIntegrationFields.ItensNotaFiscalINData listItemInvoice = new TemplateDataIntegrationFields.ItensNotaFiscalINData();
        listItemInvoice.notaFiscal = '1620';
        listItemInvoice.codigoMaterial ='100';
        listItemInvoice.quantidade = 12;
        listItemInvoice.valorTotalItem = 1020;
        listItemInvoice.lote ='1';
        listItemInvoice.unidadeMedida ='1';
        listItemInvoice.naturezaOperacao ='Venda de mercadoria';
        listItemInvoice.descontoNF = 1;
        listItemInvoice.valorUnitarioNF = 4;
        listItemsList.add(listItemInvoice);

        List<TemplateDataIntegrationFields.NotaFiscalINData> listInvoiceList = new List<TemplateDataINtegrationFields.NotaFiscalINData>();
        TemplateDataIntegrationFields.NotaFiscalINData listInvoice = new TemplateDataINtegrationFields.NotaFiscalINData();
        listInvoice.invoiceName = '1620';
        listInvoice.numeroNotaFiscal = '1620';
        listInvoice.cliente = '100';
        listInvoice.numeroPedido = '100';
        listInvoice.codigoEmpresa = '1';
        listInvoice.propriedade = '100';
        listInvoice.serie = '001';
        listInvoice.localNegocios = 'Minas Gerais';
        listInvoice.codigoStatus = '1';
        listInvoice.chaveAcesso = '3511.0444.4631.5600.0184.5505.9000.1947.4412.0510.2788';
        listInvoice.valorTotalNf = 110;
        listInvoice.naturezaOperacao = '09090945';
        listInvoice.itensNotaFiscal = listItemsList;
        listInvoiceList.add(listInvoice);

        IntegrationINInvoice.ResponseModel modelo = IntegrationINInvoice.upsertInvoice(listInvoiceList);
    }
}