force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de Pagamento</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CondicaoPagamento__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cultura__c/Cultura__c.object-meta.xml
<CustomObject>
    <label>Cultura</label>
    <nameField>
        <label>Nome de Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Cultura</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cultura__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Cultura</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Cultura__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerOrderNumber__c</fullName>
    <label>Número Pedido Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipName>PedidosCondicao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDate__c</fullName>
    <label>Data de Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentForm__c.field-meta.xml
<CustomField>
    <fullName>PaymentForm__c</fullName>
    <label>Forma de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Cessão Crédito</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Boleto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Operação Barter</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dinheiro/Adiantamento</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Encontro de Contas</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>Cheque Recebido</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>DOC</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Operação CRA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>TED</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>DOC/TED</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Transferência</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>PIX</label>
            </value>
            <value>
                <fullName>Bonificação</fullName>
                <isActive>false</isActive>
                <label>Bonificação</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SalesCTV__c.field-meta.xml
<CustomField>
    <fullName>SalesCTV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CTV da Venda</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente Entrega</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingDate__c.field-meta.xml
<CustomField>
    <fullName>ShippingDate__c</fullName>
    <label>Data de Entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/StatusSF__c.field-meta.xml
<CustomField>
    <fullName>StatusSF__c</fullName>
    <label>Status SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em digitação</fullName>
                <default>true</default>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Em aprovação - Gerente Filial</fullName>
            </value>
            <value>
                <fullName>Em Aprovação - Gerente Regional</fullName>
            </value>
            <value>
                <fullName>Em Aprovação - Diretor</fullName>
            </value>
            <value>
                <fullName>Em Aprovação - Diretor Torre</fullName>
            </value>
            <value>
                <fullName>Em Aprovação - Comitê Margem</fullName>
            </value>
            <value>
                <fullName>Em Aprovação - Mesa de Grãos</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/NumeroSap__c.field-meta.xml
<CustomField>
    <fullName>NumeroSap__c</fullName>
    <label>Número Sap</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/UnitMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasure__c</fullName>
    <label>Unidade de Medida</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Código Sap</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ClasseAvaliacao__c.field-meta.xml
<CustomField>
    <fullName>ClasseAvaliacao__c</fullName>
    <label>Classe Avaliação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/GrupoQuimico__c.field-meta.xml
<CustomField>
    <fullName>GrupoQuimico__c</fullName>
    <label>Grupo Químico</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MarcadoEliminacao__c.field-meta.xml
<CustomField>
    <fullName>MarcadoEliminacao__c</fullName>
    <label>Marcado Eliminação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NCM__c.field-meta.xml
<CustomField>
    <fullName>NCM__c</fullName>
    <label>NCM</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroRegistro__c.field-meta.xml
<CustomField>
    <fullName>NumeroRegistro__c</fullName>
    <externalId>true</externalId>
    <label>Número Registro</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OrigemMaterial__c.field-meta.xml
<CustomField>
    <fullName>OrigemMaterial__c</fullName>
    <label>Origem Material</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de Medida</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/BillingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BillingStartDate__c</fullName>
    <label>Data Inicio Faturament</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Safra</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateBilling__c.field-meta.xml
<CustomField>
    <fullName>EndDateBilling__c</fullName>
    <label>Data Fim Faturamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateInsertionOrders__c.field-meta.xml
<CustomField>
    <fullName>EndDateInsertionOrders__c</fullName>
    <label>Data Fim Inserção Pedidos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Safra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/NumberOfDaysAfterPayment__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterPayment__c</fullName>
    <label>Quantidade de Dias Após Pagamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/PaymentBaseDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentBaseDate__c</fullName>
    <label>Data Base Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/ReleaseStatus__c.field-meta.xml
<CustomField>
    <fullName>ReleaseStatus__c</fullName>
    <label>Status Liberação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safra__c/fields/StartDateOrderInsertion__c.field-meta.xml
<CustomField>
    <fullName>StartDateOrderInsertion__c</fullName>
    <label>Data Inicio Inserção Pedidos</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CallExcludePageControllerTest.cls
@isTest
public class CallExcludePageControllerTest {
    @testSetup public static void makeData() {
        Account parentAccount = new Account(
            Name = 'Parent Account',
            Company__c = 'Parent Account',
            Phone = '11111111111',
            ExternalId__c = '123456'
        );
        insert parentAccount;

        Safra__c crop = new Safra__c(
            Name = 'Safra 01',
            Code__c = '001',
            BillingStartDate__c = System.today(),
            StartDateOrderInsertion__c = System.today(),
            EndDateBilling__c = System.today().addDays(90),
            EndDateInsertionOrders__c = System.today().addDays(90),
            NumberOfDaysAfterPayment__c = System.today().addDays(10),
            PaymentBaseDate__c = System.today().addDays(90),
            ReleaseStatus__c = 'Ativo'
        );
        insert crop;

        Cultura__c culture = new Cultura__c(
            Name = 'Culture 01',
            Name__c = 'Culture 01',
            Codigo__c = '001'
        );
        insert culture;

        CondicaoPagamento__c paymentCondition = new CondicaoPagamento__c(
            Name = 'Boleto',
            Code__c = '001'
        );
        insert paymentCondition;

        Order order = new Order(
            RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Venda Normal').getRecordTypeId(),
            AccountId = parentAccount.Id,
            Status = '0',
            PriceBook2Id = Test.getStandardPricebookId(),
            Type = 'Venda Normal',
            ShippingAccount__c = parentAccount.Id,
            PaymentDate__c = Date.today().addDays(-2),
            CustomerOrderNumber__c = '65465',
            EffectiveDate = Date.today(),
            PaymentForm__c = 'A',
            Currency__c = 'BRL',
            StatusSF__c = 'Em digitação',
            Incoterms__c = 'CIF',
            Crop__c = crop.Id,
            Culture__c = culture.Id,
            SalesCTV__c = UserInfo.getUserId(),
            PaymentCondition__c = paymentCondition.Id,
            ShippingDate__c = Date.today().addDays(2)
        );
        insert order;

        Product2 prod = new Product2(
            Name = 'Laptop X200', 
            Family = 'Hardware',
            ExternalId__c = '0001',
            ClasseAvaliacao__c = 'av01',
            GrupoQuimico__c = 'bg1',
            MarcadoEliminacao__c = 'tes01',
            NCM__c = '85432000',
            NumeroRegistro__c = '2',
            OrigemMaterial__c = 'sp',
            UnidadeMedida__c = 'un'
        );
        insert prod;
        
        OrderItem orderItem = new OrderItem(
            OrderId = order.Id,
            Product2Id = prod.Id,
            NumeroSap__c = '123',
            UnitMeasure__c = 'L',
            UnitPrice = 10000,
            Quantity = 1,
            ExternalId__c = 'texto',
            PricebookEntryId = [SELECT Id FROM PricebookEntry WHERE Product2Id =: prod.Id LIMIT 1][0].Id
        );
        insert orderItem;
    }

    @isTest public static void excludeItemTest() {
        // PageReference pageRef = Page.CallExcludePage;
        // Test.setCurrentPage(pageRef);

        OrderItem orderItem = [SELECT Id FROM OrderItem];
        ApexPages.StandardController sc = new ApexPages.standardController(orderItem);
      
        CallExcludePageController controller = new CallExcludePageController(sc);
    }
}