force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultura__c/Cultura__c.object-meta.xml
<CustomObject>
    <label>Cultura</label>
    <nameField>
        <label>Nome de Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Cultura</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cultura__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Cultura</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Centro de distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centro de distribuições</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionCenter__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Centro de Distribuições</relationshipLabel>
    <relationshipName>CentroDistribuicao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/JurosDescontoAntecipao__c.object-meta.xml
<CustomObject>
    <label>Lista de Preço</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Lista de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listas de Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JurosDescontoAntecipao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Sap</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>SUBSTITUTE(SUBSTITUTE( TRIM( SUBSTITUTE( Product__r.ProductCode &amp; &quot;!&quot; , &quot;0&quot;, &quot; &quot;)), &quot; &quot;, &quot;0&quot;), &quot;!&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código do Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Juros e Descontos Antecipação</relationshipLabel>
    <relationshipName>Juros_e_Descontos_Antecipa_o</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Listas de Preço</relationshipLabel>
    <relationshipName>Juros_e_Descontos_Antecipa_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JurosDescontoAntecipao__c/recordTypes/ZDAN.recordType-meta.xml
<RecordType>
    <fullName>ZDAN</fullName>
    <active>true</active>
    <label>Desconto</label>
</RecordType>

force-app/main/default/objects/JurosDescontoAntecipao__c/recordTypes/ZPR0.recordType-meta.xml
<RecordType>
    <fullName>ZPR0</fullName>
    <active>true</active>
    <label>Preço</label>
</RecordType>

force-app/main/default/objects/Product2/fields/ClasseAvaliacao__c.field-meta.xml
<CustomField>
    <fullName>ClasseAvaliacao__c</fullName>
    <label>Classe Avaliação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/GrupoQuimico__c.field-meta.xml
<CustomField>
    <fullName>GrupoQuimico__c</fullName>
    <label>Grupo Químico</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MarcadoEliminacao__c.field-meta.xml
<CustomField>
    <fullName>MarcadoEliminacao__c</fullName>
    <label>Marcado Eliminação</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NCM__c.field-meta.xml
<CustomField>
    <fullName>NCM__c</fullName>
    <label>NCM</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroRegistro__c.field-meta.xml
<CustomField>
    <fullName>NumeroRegistro__c</fullName>
    <externalId>true</externalId>
    <label>Número Registro</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OrigemMaterial__c.field-meta.xml
<CustomField>
    <fullName>OrigemMaterial__c</fullName>
    <label>Origem Material</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de Medida</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductGroup__c/ProductGroup__c.object-meta.xml
<CustomObject>
    <label>Grupo de Produto</label>
    <nameField>
        <label>Nome do Grupo de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupo de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductGroup__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/BillingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BillingStartDate__c</fullName>
    <label>Data Inicio Faturament</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Safra</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateBilling__c.field-meta.xml
<CustomField>
    <fullName>EndDateBilling__c</fullName>
    <label>Data Fim Faturamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/EndDateInsertionOrders__c.field-meta.xml
<CustomField>
    <fullName>EndDateInsertionOrders__c</fullName>
    <label>Data Fim Inserção Pedidos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome da Safra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/NumberOfDaysAfterPayment__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterPayment__c</fullName>
    <label>Quantidade de Dias Após Pagamento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Safra__c/fields/ReleaseStatus__c.field-meta.xml
<CustomField>
    <fullName>ReleaseStatus__c</fullName>
    <label>Status Liberação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safra__c/fields/StartDateOrderInsertion__c.field-meta.xml
<CustomField>
    <fullName>StartDateOrderInsertion__c</fullName>
    <label>Data Inicio Inserção Pedidos</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Equipe de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IntegrationINPricebook2Test.cls
@isTest
public class IntegrationINPricebook2Test {
  
    @TestSetup
    static void makeData(){


        Account account = new Account(
            Name = 'Teste 1',
            BillingStreet = ' ',
            BillingState = '' ,
            Phone= '', 
            BillingCity = ' ', 
            BillingLongitude = 000000,
            BillingLatitude = 00000,
            BillingPostalCode = '',
            ExternalId__c = '11111',
            Company__c = 'Empresa 1'
        );

        Safra__c safra = new Safra__c(
            Code__c = '1223',
            Name = 'Safra Teste',
            Name__c = 'Safra Teste',
            BillingStartDate__c = System.today(),
            EndDateBilling__c = System.today(),
            EndDateInsertionOrders__c = System.today(),
            NumberOfDaysAfterPayment__c = System.today(),
            ReleaseStatus__c = 'Ativo',
            StartDateOrderInsertion__c = System.today()

        );

        Cultura__c cultura = new Cultura__c(
            Name = 'Safrinha',
            Name__c = 'Safrinha',
            Codigo__c = '1234'
        );

        SalesOrg__c so = new SalesOrg__c(
            Name = 'AgroGalaxy',
            SalesOrganizationCode__c = '1111'
        );

        // ClasseAvaliacao__c, GrupoQuimico__c, MarcadoEliminacao__c, NCM__c, NumeroRegistro__c, 
        // OrigemMaterial__c, UnidadeMedida__c]: 
        Product2 prod = new Product2(
            Name = 'Laptop X200', 
            Family = 'Hardware',
            ExternalId__c = '0001',
            ProductCode__c = '0002',
            ClasseAvaliacao__c = 'chucrute',
            GrupoQuimico__c = 'Só o quimico',
            MarcadoEliminacao__c = 'S',
            NCM__c = 'S',
            NumeroRegistro__c = '0001',
            OrigemMaterial__c = 'Himalaia',
            UnidadeMedida__c = 'KG'
        );
        
        SalesOffice__c salesOffice = new SalesOffice__c(
            Name = 'Escritório Teste',
            Codigo__c = '1'

        );
        SalesTeam__c salesTeam = new SalesTeam__c(
            Name = 'Equipe Teste',
            ExternalId__c = '1'
        );

        
        ActivitySector__c activitySector = new ActivitySector__c(
            Name = 'Setor Teste',
            Codigo__c = '1'
        );
        

        ProductFamily__c productFamily = new ProductFamily__c(
            Name = 'Família Teste',
            ExternalId__c = '1'
        );

        ProductGroup__c productGroup = new ProductGroup__c(
            Name = 'Grupo Teste',
            ExternalId__c = '1'
        );

        salesCondition__c sales = new salesCondition__c(
            Name = 'Condição',
            ExternalId__c = '1'
        );

        DistributionCenter__c dc = new DistributionCenter__c(
            Name = 'Teste Centro',
            Code__c = '1'
        );
        
        


      INSERT dc;
      INSERT sales;  
      INSERT account;
      INSERT safra;
      INSERT cultura;
      INSERT so;
      INSERT prod;
    //   INSERT prod2;
      INSERT salesOffice;
      INSERT salesTeam;
      INSERT activitySector;
      INSERT productFamily;
      INSERT productGroup; 
        
        JurosDescontoAntecipao__c ListPrice = new JurosDescontoAntecipao__c(
            RecordTypeId = Schema.SObjectType.JurosDescontoAntecipao__c.getRecordTypeInfosByDeveloperName().get('ZPR0').getRecordTypeId(),
            SalesOrg__c = so.Id,
            Currency__c = 'BRL',
            harvest__c = safra.Id,
            SalesCondition__c = sales.Id,
            Account__c = account.Id,
            Product__c = prod.Id,
            StartDate__c = Date.valueOf('2022-03-30')
        );
        
        INSERT ListPrice;
    }

    @isTest
    static void verifyIntegrationPricebook2(){

        List<TemplateDataIntegrationFields.JurosDescontoAntecipaoINData> listPriceList = new List<TemplateDataIntegrationFields.JurosDescontoAntecipaoINData>();
        TemplateDataIntegrationFields.JurosDescontoAntecipaoINData listPrice = new TemplateDataIntegrationFields.JurosDescontoAntecipaoINData();
        listPrice.table = 'A935';
        listPrice.accountCode = '11111';
        listPrice.typeCondition = 'ZPR0';
        listPrice.product = '0002';
        listPrice.productGroup = '1';
        listPrice.multiplicationFactor = '1';
        listPrice.unitPrice = '2.00';
        listPrice.center = '1';
        listPrice.salesCondition = '1';
        listPrice.cropCode = '1223';
        listPrice.cultureCode = '1234';
        listPrice.accountGroup = '04';
        listPrice.orgVendas = '1111';
        listPrice.salesOffice = '1';
        listPrice.salesTeam = '1';
        listPrice.initialDate = '2022-03-30';
        listPrice.endDate = '2022-03-30';
        listPrice.typeCurrency = 'BRL';
        listPrice.externalId = 'Jurema';
        listPrice.unitMeasurement = 'LT';
        
        TemplateDataIntegrationFields.JurosDescontoAntecipaoINData listPrice2 = new TemplateDataIntegrationFields.JurosDescontoAntecipaoINData();
        listPrice2.table = 'A935';
        listPrice2.accountCode = '11111';
        listPrice2.typeCondition = 'ZPRS';
        listPrice2.product = '0002';
        listPrice2.productGroup = '1';
        listPrice2.multiplicationFactor = '1';
        listPrice2.unitPrice = '1.99';
        listPrice2.center = '1';
        listPrice2.salesCondition = '1';
        listPrice2.cropCode = '1223';
        listPrice2.cultureCode = '1234';
        listPrice2.accountGroup = '04';
        listPrice2.orgVendas = '1111';
        listPrice2.salesOffice = '1';
        listPrice2.salesTeam = '1';
        listPrice2.initialDate = '2022-03-30';
        listPrice2.endDate = '2022-03-30';
        listPrice2.typeCurrency = 'BRL';
        listPrice2.externalId = 'Jurema2';
        listPrice2.unitMeasurement = 'LT';
        listPriceList.add(listPrice2);
        
        TemplateDataIntegrationFields.JurosDescontoAntecipaoINData listPrice3 = new TemplateDataIntegrationFields.JurosDescontoAntecipaoINData();
        listPrice3.table = 'A935';
        listPrice3.accountCode = '11111';
        listPrice3.typeCondition = 'ZCPE';
        listPrice3.product = '0002';
        listPrice3.productGroup = '1';
        listPrice3.multiplicationFactor = '1';
        listPrice3.unitPrice = '3.00';
        listPrice3.center = '1';
        listPrice3.salesCondition = '1';
        listPrice3.cropCode = '1223';
        listPrice3.cultureCode = '1234';
        listPrice3.accountGroup = '04';
        listPrice3.orgVendas = '1111';
        listPrice3.salesOffice = '1';
        listPrice3.salesTeam = '1';
        listPrice3.initialDate = '2022-03-30';
        listPrice3.endDate = '2022-03-30';
        listPrice3.typeCurrency = 'BRL';
        listPrice3.externalId = 'Jurema3';
        listPrice3.unitMeasurement = 'LT';
        listPriceList.add(listPrice3);
        
        TemplateDataIntegrationFields.JurosDescontoAntecipaoINData listPrice4 = new TemplateDataIntegrationFields.JurosDescontoAntecipaoINData();
        listPrice4.table = 'A934';
        listPrice4.accountCode = '11111';
        listPrice4.typeCondition = 'ZDAN';
        listPrice4.product = '0002';
        listPrice4.productGroup = '1';
        listPrice4.multiplicationFactor = '1';
        listPrice4.unitPrice = '3.00';
        listPrice4.center = '1';
        listPrice4.salesCondition = '1';
        listPrice4.cropCode = '1223';
        listPrice4.cultureCode = '1234';
        listPrice4.accountGroup = '04';
        listPrice4.orgVendas = '1111';
        listPrice4.salesOffice = '1';
        listPrice4.salesTeam = '1';
        listPrice4.initialDate = '2022-03-30';
        listPrice4.endDate = '2022-03-30';
        listPrice4.typeCurrency = '%';
        listPrice4.externalId = 'Jurema4';
        listPrice4.unitMeasurement = 'LT';
        listPriceList.add(listPrice4);

        Test.startTest();
        IntegrationINPricebook2.ResponseModel model = IntegrationINPricebook2.upsertPricebook2(listPriceList);
        IntegrationINPricebook2.ResponseModel toPass = new IntegrationINPricebook2.ResponseModel(model.response);
        model = IntegrationINPricebook2.upsertPricebook2(listPriceList);
        toPass = new IntegrationINPricebook2.ResponseModel(model.response);
        Test.stopTest();
        
        System.debug(model);
        System.assertEquals(true, model.response[0].status, 'O status nesta situação deveria vir verdadeiro');
        System.assertEquals('JurosDescontoAntecipao__c', model.response[0].sObjectType, 'O objeto nesta situação deveria vir JurosDescontoAntecipao__c');
        System.assertEquals(null, model.response[0].errorMessage, 'O erro nesta situação deveria vir nulo');
        System.assertNotEquals(null, model.response[0].idSalesforce, 'O idSalesforce nesta situação deveria vir um Id');
        System.assertNotEquals('null', model.response[0].externalCode, 'O externalCode nesta situação deveria vir codExternal');
    }
    
    @isTest
    static void verifyException(){
        List<TemplateDataIntegrationFields.JurosDescontoAntecipaoINData> listPriceList = new List<TemplateDataIntegrationFields.JurosDescontoAntecipaoINData>();
        TemplateDataIntegrationFields.JurosDescontoAntecipaoINData listPrice = new TemplateDataIntegrationFields.JurosDescontoAntecipaoINData();
        listPrice.table = 'A935';
        listPrice.accountCode = '11111';
        listPrice.typeCondition = 'ZPR0';
        listPrice.product = '0002';
        listPrice.productGroup = '1';
        listPrice.multiplicationFactor = '1';
        listPrice.unitPrice = '2.00';
        listPrice.center = '1';
        listPrice.salesCondition = '1';
        listPrice.cropCode = '1223';
        listPrice.cultureCode = '1234';
        listPrice.accountGroup = '04';
        //listPrice.orgVendas = '1111';
        listPrice.salesOffice = '1';
        listPrice.salesTeam = '1';
        listPrice.initialDate = '2022-03-30';
        listPrice.endDate = '2022-03-30';
        listPrice.typeCurrency = 'BRL';
        listPrice.externalId = 'Jurema';
        listPrice.unitMeasurement = 'LT';
        listPriceList.add(listPrice);
        
        Test.startTest();
        IntegrationINPricebook2.ResponseModel model = IntegrationINPricebook2.upsertPricebook2(listPriceList);
        IntegrationINPricebook2.ResponseModel toPass = new IntegrationINPricebook2.ResponseModel(model.response);
        Test.stopTest();
        
        System.debug(model);
        System.assertEquals(false, model.response[0].status, 'O status nesta situação deveria vir falsa');
        System.assertEquals('JurosDescontoAntecipao__c', model.response[0].sObjectType, 'O objeto nesta situação deveria vir JurosDescontoAntecipao__c');
    }
}