force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletos__c/Boletos__c.object-meta.xml
<CustomObject>
    <label>Boleto</label>
    <nameField>
        <label>Nome de Boleto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boletos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletos__c/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Código do Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Boletos</relationshipLabel>
    <relationshipName>Boletos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Empresa</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Data de Vencimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <label>Data de Emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Boletos</relationshipLabel>
    <relationshipName>Boletos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boletos__c/fields/WritableLine__c.field-meta.xml
<CustomField>
    <fullName>WritableLine__c</fullName>
    <externalId>true</externalId>
    <label>Linha Digitável</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/pdfBoletoControllerTest.cls
@isTest
public with sharing class pdfBoletoControllerTest {
    public  pdfBoletoControllerTest() {}
        @TestSetup
        static void makeData(){
            Account account = new Account(
                Name = 'Testinho11',
                BillingStreet = '',
                BillingState = '' ,
                Phone= '0000011111',
                BillingCity = ' ',
                BillingLongitude = 000000,
                BillingLatitude = 000000,
                BillingPostalCode = '',
                ExternalId__c = '020',
                Company__c = 'Empresa 012'
            );
            insert account;
            SalesOrg__c so = new SalesOrg__c(
                Name = 'AgroGalaxy',
                SalesOrganizationCode__c = '1111'
            );
            insert so;
            Boletos__c boletos = new Boletos__c(
                AccountCode__c = account.Id,
                ExpirationDate__c = Date.valueOf('2022-09-21'),
                IssueDate__c = Date.valueOf('2022-09-21'),
                SalesOrg__c = so.Id,
                Value__c = 20.00,
                WritableLine__c = '002'
            );
            insert boletos;
        }
        @isTest
        static void BoletosExtension_UnitTest(){
            Pagereference pageRef = Page.BoletoPagePDF;
            Test.setCurrentPage(pageRef);
            Boletos__c boletos = [SELECT Id, WritableLine__c,Name FROM Boletos__c LIMIT 1][0];
             pageRef.getParameters().put('Id', String.valueOf([SELECT Id FROM Boletos__c LIMIT 1].Id));
            ApexPages.StandardController stdController = new ApexPages.StandardController([SELECT Id FROM Boletos__c LIMIT 1][0]);
			Test.setMock(HttpCalloutMock.class, new CalloutBoletoPdfMock(true, String.valueOf(boletos.WritableLine__c), false));
            Test.startTest();
            BoletosPdfController boletoExt = new BoletosPdfController(stdController);
            Test.stopTest();
        }
        
        @isTest
        static void vefifyConstructor(){
        PageReference pageRef = Page.BoletoPagePDF;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf([SELECT Id FROM Boletos__c LIMIT 1].Id));
        ApexPages.StandardController sc = new ApexPages.StandardController([SELECT Id FROM Boletos__c LIMIT 1][0]);
         Test.setMock(HttpCalloutMock.class, new CalloutBoletoPdfMock(true, String.valueOf([SELECT Id, WritableLine__c FROM Boletos__c LIMIT 1][0].WritableLine__c), false));
         Test.startTest();
         BoletosPdfController boletosController = new BoletosPdfController(sc);
         Test.stopTest();
        }
    @isTest
     static void calloutBoletoToken(){
        Test.setMock(HttpCalloutMock.class, new CalloutBoletoPdfMock(true, '0000023', true));
        Test.startTest();
        String response = BoletosPdfController.getAcessCode();
        Test.stopTest();
        System.assertEquals('fdgfdbvkhjfdv', response, 'O access_token devia vir preenchido');
    }
}