force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Razão Social</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivitySector__c/ActivitySector__c.object-meta.xml
<CustomObject>
    <label>Setor de Atividade</label>
    <nameField>
        <label>Setor de Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Setor de Atividade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ActivitySector__c.field-meta.xml
<CustomField>
    <fullName>ActivitySector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Setor de Atividade</label>
    <referenceTo>ActivitySector__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/ClientGroup__c.field-meta.xml
<CustomField>
    <fullName>ClientGroup__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NÃO SEGMENTADO</fullName>
            </value>
            <value>
                <fullName>REDISTRIBUIÇÃO</fullName>
            </value>
            <value>
                <fullName>MODULAR</fullName>
            </value>
            <value>
                <fullName>CLÁSSICO</fullName>
            </value>
            <value>
                <fullName>INOVADOR</fullName>
            </value>
            <value>
                <fullName>CLUBE A</fullName>
            </value>
            <value>
                <fullName>CONECTA</fullName>
            </value>
            <value>
                <fullName>DINAMICO</fullName>
                <label>DINÂMICO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de Distribuição</label>
    <referenceTo>DistributionChannel__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SupplierCenter__c.field-meta.xml
<CustomField>
    <fullName>SupplierCenter__c</fullName>
    <label>Centro Fornecedor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributionChannel__c/DistributionChannel__c.object-meta.xml
<CustomObject>
    <label>Canal de Distribuição</label>
    <nameField>
        <label>Canal de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionChannel__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <label>Escritório Venda</label>
    <nameField>
        <label>Nome do Escritório Venda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritório Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Equipe de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchCTVSchedulableTest.cls
@isTest
    public with sharing class BatchCTVSchedulableTest {

        @TestSetup
        static void makeData(){
    
            Account account = new Account(
                Name = 'Teste 1',
                BillingStreet = ' ',
                BillingState = '' ,
                Phone= '', 
                BillingCity = ' ', 
                BillingLongitude = 000000,
                BillingLatitude = 00000,
                BillingPostalCode = '',
                ExternalId__c = '11111',
                Company__c = 'Empresa 01'
            );
            insert account;
    
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testes_CTV_TEST@testes.com');
    
            insert u;
    
            SalesOrg__c salesOrg = new SalesOrg__c(
                Name = 'AgroGalaxy',
                SalesOrganizationCode__c = '1111'
            );
            insert salesOrg;
            DistributionChannel__c distributionChannel = new DistributionChannel__c(
                Name = 'Teste',
                Codigo__c = '0001'
            );
            insert distributionChannel;
    
            SalesOffice__c salesOffice = new SalesOffice__c(
                Name = 'Sales Office',
                Codigo__c = '001'
            );
            insert salesOffice;
    
            SalesTeam__c salesTeam = new SalesTeam__c(
                Name = 'Sales team',
                ExternalId__c = '001'
            );
            insert salesTeam;
    
            ActivitySector__c activitySector = new ActivitySector__c(
                Name = 'Teste Activity',
                Codigo__c = '003'
            );
            insert activitySector;
    
            Company__c company = new Company__c(
                Name = 'Company',
                Blocked__c = false,
                ClientGroup__c = '11',
                Conta__c = account.Id,
                SalesOrg__c = salesOrg.Id,
                SalesOffice__c = salesOffice.Id,
                SalesTeam__c = salesTeam.Id,
                ActivitySector__c = activitySector.Id,
                DistributionChannel__c = distributionChannel.Id,
                ExternalID__c = '001',
                SupplierCenter__c = '1010'
            );
            insert company;
        }

        @isTest
        public static void testBatchDeliveryNotificationSchedulable(){
            String sch = '0 0 * * * ?';
            Test.startTest();
            System.schedule('Delivery Notification Schedule Job Test Class', sch, new BatchCTVSchedulable());
            Test.stopTest();
        }
        // @isTest
        // public static void testBatchImplementationCTV(){
        //     Account account = [SELECT Id FROM Account LIMIT 1];
        //     User u = [SELECT Id FROM User WHERE UserName='testes_CTV_TEST@testes.com' LIMIT 1];
        //     Territory2Type terrModel = [SELECT Id FROM Territory2Type LIMIT 1];
        //     Territory2Model model = [SELECT Id FROM Territory2Model LIMIT 1];
        //     Territory2 objTerr = new Territory2(); 
        //         objTerr.Description = 'Description__c';
        //         objTerr.Name = 'Name';
        //         objTerr.DeveloperName = 'Name';
        //         objTerr.Territory2TypeId = terrModel.Id;
        //         objTerr.Territory2ModelId = model.Id;
        //     insert objTerr;

        //     UserTerritory2Association userTerrAssociation = new UserTerritory2Association(Territory2Id= objTerr.Id, UserId= u.Id, RoleInTerritory2='Sales / Marketing Manager');
        //     insert userTerrAssociation;
        //     String sch = '0 0 * * * ?';
        //     Test.startTest();
        //     BatchImplementationCTV.run();
        //     Test.stopTest();
        // }
    }