force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cultura__c/Cultura__c.object-meta.xml
<CustomObject>
    <label>Cultura</label>
    <nameField>
        <label>Nome de Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Cultura</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fotos__c/Fotos__c.object-meta.xml
<CustomObject>
    <label>Foto</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Fotos Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fotos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fotos__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/FotoControl__c.field-meta.xml
<CustomField>
    <fullName>FotoControl__c</fullName>
    <label>Foto Item</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/IsIntegrated__c.field-meta.xml
<CustomField>
    <fullName>IsIntegrated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lembrete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/Observation__c.field-meta.xml
<CustomField>
    <fullName>Observation__c</fullName>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/RTR__c.field-meta.xml
<CustomField>
    <fullName>RTR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTR</label>
    <referenceTo>TechnicalReport__c</referenceTo>
    <relationshipLabel>Fotos</relationshipLabel>
    <relationshipName>Fotos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting para habilitar e desabilitar integrações</description>
    <label>Integração</label>
</CustomObject>

force-app/main/default/objects/Integration__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <length>255</length>
    <label>Token</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__c/fields/UrlToken__c.field-meta.xml
<CustomField>
    <fullName>UrlToken__c</fullName>
    <label>URL Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Safra</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/TechnicalReport__c.object-meta.xml
<CustomObject>
    <description>RTR</description>
    <label>Relatório Técnico</label>
    <nameField>
        <displayFormat>RTR-{0000}</displayFormat>
        <label>Relatório Técnico Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relatórios Técnicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalReport__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data da Finalização</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Horário da Finalização</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Observações</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerado</fullName>
                <default>true</default>
                <label>Gerado</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/VisitPlanning__c.field-meta.xml
<CustomField>
    <fullName>VisitPlanning__c</fullName>
    <label>Visita</label>
    <referenceTo>VisitPlanning__c</referenceTo>
    <relationshipLabel>Relatórios Técnicos</relationshipLabel>
    <relationshipName>Relatorios_Tecnicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/VisitPlanning__c.object-meta.xml
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Planejamento da Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamento de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/fields/BP_Property__c.field-meta.xml
<CustomField>
    <fullName>BP_Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BP Propriedade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.BpType__c</field>
            <operation>equals</operation>
            <value>Propriedade</value>
        </filterItems>
        <filterItems>
            <field>$Source.Main_BP__c</field>
            <operation>equals</operation>
            <valueField>Account.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planejamento de Visitas (BP Propriedade)</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Motivo do Cancelamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Cultura__c</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Displacement__c.field-meta.xml
<CustomField>
    <fullName>Displacement__c</fullName>
    <label>Houve Deslocamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data Fim do Plano</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Horário Final</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <displayFormat>{000000000}</displayFormat>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/InitialDate__c.field-meta.xml
<CustomField>
    <fullName>InitialDate__c</fullName>
    <label>Data de Início do Plano</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/MainBP__c.field-meta.xml
<CustomField>
    <fullName>MainBP__c</fullName>
    <label>BP Principal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.BpType__c</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Observação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Geração de demanda</fullName>
            </value>
            <value>
                <fullName>Acompanhamento técnico</fullName>
            </value>
            <value>
                <fullName>Acompanhamento colheita</fullName>
            </value>
            <value>
                <fullName>Cobrança</fullName>
            </value>
            <value>
                <fullName>Coleta de Documentos</fullName>
            </value>
            <value>
                <fullName>Coleta assinatura doctos</fullName>
            </value>
            <value>
                <fullName>Fechamento e Planej. de Safra</fullName>
            </value>
            <value>
                <fullName>Evento</fullName>
            </value>
            <value>
                <fullName>Treinamento e Reunião</fullName>
            </value>
            <value>
                <fullName>Ocorrência</fullName>
            </value>
            <value>
                <fullName>Entrega de Produto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Presential__c.field-meta.xml
<CustomField>
    <fullName>Presential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Presencial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Reminder__c.field-meta.xml
<CustomField>
    <fullName>Reminder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lembrete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/RTR__c.field-meta.xml
<CustomField>
    <fullName>RTR__c</fullName>
    <label>RTR Gerado</label>
    <summaryFilterItems>
        <field>TechnicalReport__c.Status__c</field>
        <operation>equals</operation>
        <value>Gerado</value>
    </summaryFilterItems>
    <summaryForeignKey>TechnicalReport__c.VisitPlanning__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Planejamento de Visitas</relationshipLabel>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Horário Inicial</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agendado</fullName>
                <default>true</default>
                <label>Agendado</label>
            </value>
            <value>
                <fullName>Reagendado</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
            <value>
                <fullName>Atrasado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalloutVisits.cls
public without sharing class CalloutVisits {

        public static void sendOrder(List<VisitPlanning__c> planningVisitsList) {
    
            List<RequestParameters> request = new List<RequestParameters>();
            List<String> visitIdList = new List<String>();
            List<String> technicalReportIdList = new List<String>();
            List<String> photoIdList = new List<String>();
            List<String> contentDocumentIdList = new List<String>();
            for (VisitPlanning__c visit : planningVisitsList) {
                visitIdList.add(visit.Id); 
            }
            List<TechnicalReport__c> technicalReportList  = new List<TechnicalReport__c>([SELECT id, ExternalId__c, Note__c, VisitPlanning__c, EndTime__c, EndDate__c, Status__c, CancellationReason__c FROM TechnicalReport__c WHERE VisitPlanning__c =: visitIdList]);
            Map<String, List<TechnicalReport__c>> technicalReportMap = new Map<String, List<TechnicalReport__c>>();
            for (VisitPlanning__c technical : technicalReportList) {
                technicalReportIdList.add(technical.Id); 

                if(technicalReportMap.containsKey(technical.VisitPlanning__c)){
                    List<VisitPlanning__c> technicalReportList = technicalReportMap.get(technical.VisitPlanning__c);
                    technicalReportList.add(technical);
                    technicalReportMap.put(comp.Conta__r.ExternalId__c,technicalReportList);
                }else{
                    List<VisitPlanning__c> newTechnicalReportList = new List<VisitPlanning__c>();
                    newTechnicalReportList.add(technical);
                    technicalReportMap.put(technical.VisitPlanning__c,newTechnicalReportList);
                }
            }
            List<Fotos__c> photoList  = new List<Fotos__c>([SELECT id, RTR__c, Observation__c, FotoControl__c, IsIntegrated__c FROM Fotos__c WHERE RTR__c =: technicalReportIdList AND IsIntegrated__c = false]);

            for(Fotos__c fotos : photoList){
                photoIdList.add(fotos.id);
            }
            List<ContentDocumentLink> contendLinkList = new List<ContentDocumentLink>([SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN: photoIdList]);
            for(ContentDocumentLink contendLink : contendLinkList){
                contentDocumentIdList.add(contendLink.ContentDocumentId);
            }
            Map<Id,ContentVersion> contendVersionList = new Map<Id,ContentVersion>([SELECT Id, VersionData FROM ContentVersion WHERE Id IN: contentDocumentIdList]);


            //para pegar o base64
            /* usando o VersionData
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(URL.getSalesforceBaseUrl().toExternalForm() + '/services/data/v42.0/sobjects/ContentVersion/06890000003oTkqAAE/VersionData');
            req.setMethod('GET');
            req.setHeader('Authorization', 'OAuth ' + UserInfo.getSessionId());
            req.setHeader('Content-Type', 'application/json');
            HttpResponse res = h.send(req);
            system.debug(res.getBody());
            */

            // por aqui

            for (VisitPlanning__c visit : planningVisitsList) {
                //criar map string,List technicalReport 
                List<VisitPlanning__c> technicalReportList = technicalReportMap.get(visit.Id); 
                request.add(new RequestParameters(visit,technicalReportList));
                
            }
            String code = (!Test.isRunningTest() ? getAcessCode() : 'acessToken');
            System.debug('AcessCode: '+ code);
            String payload = JSON.serialize(request);
            System.debug('PayloadCheck: '+ payload);
            /*
            //Metodo para busca de Access Token, depende de cada projeto, podendo estar presente dentro de uma custom settings ou relacionado com outra requisição.
            String accessToken = code;
            //Url mock: https://aabb2740-69b0-4737-925c-2c40367a3737.mock.pstmn.io//CalloutCTVCarteira
            //Path geralmente cadastrado dentro de ua customSettings 
            Integration__c data = Integration__c.getInstance('Visits OUT');
            String endpoint = (!Test.isRunningTest() ? data.Url__c : 'http://callout.My_Named_Credential.com/some/path');
            Map<String, String> headersMap = new Map<String, String>();
            headersMap.put('Content-type', 'application/json');
            headersMap.put('Authorization', 'Bearer '+ accessToken);
            
            IntegrationUtils.RequestResponseObject responseObject = IntegrationUtils.executeCallout(endpoint, payload, headersMap);
    
            if (responseObject.success) {
    
                HttpResponse response = responseObject.response;
    
                IntegrationLog.createLog('Visits OUT', 'OUT', response.getBody(), payload, false);
                System.debug('response.getBody(): '+ response.getBody());
            } else {
                IntegrationLog.createLog('Visits OUT', 'OUT', responseObject.exceptionObject.getMessage(), payload, true);
            } */
        }
        public static String getAcessCode(){
            /*
            Integration__c data = Integration__c.getInstance('Visits OUT');
            String payloadToken = 'grant_type=client_credentials';
            String endpointToken = (!Test.isRunningTest() ? data.UrlToken__c : 'http://callout.My_Named_Credential.com/some/path');
            Map<String, String> headersMapToken = new Map<String, String>();
            headersMapToken.put('Content-type', 'application/x-www-form-urlencoded');
            headersMapToken.put('Authorization', data.Token__c);
            IntegrationUtils.RequestResponseObject responseObject2 = IntegrationUtils.executeCallout(endpointToken, payloadToken, headersMapToken);
            
            if (responseObject2.success) {
                HttpResponse response = responseObject2.response;
                ResponseParametersToken responses = (ResponseParametersToken) JSON.deserialize(response.getBody(), ResponseParametersToken.class);
                return responses.access_token;
            } else {
                return null;
            }
            */
            return null;
        }
    
        //! Preparing data to Callout
        public class RequestParameters{
            public Object header;
    
            public RequestParameters(VisitPlanning__c visit, List<TechnicalReport__c> technicalReportList){
                CalloutVisits.HeaderInsert header = new CalloutVisits.HeaderInsert();
    
                header.Name  = visit.Name;
                header.BpCode = visit.MainBP__r.ExternalId__c;
                header.BpPropertyCode = visit.BP_Property__r.ExternalId__c;
                header.PlanStartDate = visit.InitialDate__c;
                header.PlanEndDate = visit.EndDate__c;
                header.StartTime = visit.StartTime__c;
                header.EndTime = visit.EndTime__c;
                header.Status = visit.Status__c;
                header.Objective = visit.Objetivo__c;
                header.Crop = visit.Safra__r.Code__c;
                header.Culture = visit.Culture__r.Codigo__c;
                header.Email = visit.Email__c;
                header.Presential = visit.Presential__c;
                header.Reminder = visit.Reminder__c;
                header.Displacement = visit.Displacement__c;
                header.CtvVisit = visit.VisitSeller__r.CodigoSap__c;
                header.Observation = visit.Note__c;
                header.ReasonRescheduling = visit.ReschedulingReason__c;
                header.ExternalCodeVisits = visit.ExternalId__c;
                header.ReasonCancellation = visit.CancellationReason__c;


                List<CalloutCTVCarteira.TechnicalReportsParameters> technicalReportList= new List<CalloutCTVCarteira.TechnicalReportsParameters>();
                
                for(TechnicalReport__c technical : technicalReportList){
                    technicalReportList.add(new CalloutCTVCarteira.TechnicalReportsParameters(technical));
                    System.debug('technicalReportList'+ technicalReportList);
                }
    
                header.TechnicalReports = technicalReportList;
                this.header = header;
            }
        }
        public class HeaderInsert{
            public String Name;
            public String BpCode;
            public String BpPropertyCode;
            public Date PlanStartDate;
            public Date PlanEndDate;
            public Time StartTime;
            public Time EndTime;
            public String Status;
            public String Objective;
            public String Crop;
            public String Culture;
            public String Email;
            public Boolean Presential;
            public Boolean Reminder;
            public String Displacement;
            public String CtvVisit;
            public String Observation;
            public String ReasonRescheduling;
            public String ExternalCodeVisits;
            public String ReasonCancellation;
            public List<CalloutVisits.TechnicalReportsParameters> TechnicalReports;

            public HeaderInsert(){}
        }
        public class PhotosParameters{
            public String Photo;
            public String Observation;
            public String FileLine;
            public String ExternalCodePhoto;
            public PhotosParameters(Fotos__c photo,Map<String,String> base64PhotoMap){
                //this.Photo = base64PhotoMap.get;
                //this.Observation = photo;
                //this.FileLine = photo;
            }
        }
    
        public class TechnicalReportsParameters{
            public String Observation;
            public Time EndTime;
            public Date EndDate;
            public String Status;
            public String CancellationReason;
            public String RtrLine;
            public String ExternalCodeTechnical;
            
            public List<CalloutVisits.PhotosParameters> Photos;
            public TechnicalReportsParameters(TechnicalReport__c technicalReport){
                CalloutVisits.TechnicalReportsParameters technical = new CalloutVisits.TechnicalReportsParameters();
    
                technical.Observation = technicalReport.Note__c;
                technical.EndTime = technicalReport.EndTime__c;
                technical.EndDate = technicalReport.EndDate__c;
                technical.Status = technicalReport.Status__c;
                technical.CancellationReason = technicalReport.CancellationReason__c;
                technical.RtrLine = technicalReport.rtrControl__c;
                technical.ExternalCodeTechnical = technicalReport.ExternalId__c;
            }
        }
    
        //! Response part
        public class ResponseParameters {
            public List<ResponseParametersWrapper> responses;
    
            public ResponseParameters(List<ResponseParametersWrapper> responses) {
                this.responses = responses;
            }
        }
    
        public class ResponseParametersWrapper {
            public Boolean Status; 
            public List<OrderDetails> DetalhesPedido;
            public List<Messages> Mensagens; 
        }
    
        public class ResponseParametersToken {
            public String access_token; 
            public String scope; 
            public String token_type; 
            public Decimal expires_in; 
        }
    
        public class Messages{
            public String Tipo;
            public String Mensagem;
        }
    
        public class OrderDetails{
            public String StatusSap;
            public String NumeroOrdemVenda;
        }
    }
    
}