force-app/main/default/objects/ActivitySector__c/ActivitySector__c.object-meta.xml
<CustomObject>
    <label>Setor de Atividade</label>
    <nameField>
        <label>Setor de Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Setor de Atividade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/Cultura__c.object-meta.xml
<CustomObject>
    <label>Cultura</label>
    <nameField>
        <label>Nome de Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultura__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Cultura</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Centro de distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centro de distribuições</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionCenter__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Centro de Distribuições</relationshipLabel>
    <relationshipName>CentroDistribuicao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DistributionChannel__c/DistributionChannel__c.object-meta.xml
<CustomObject>
    <label>Canal de Distribuição</label>
    <nameField>
        <label>Canal de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionChannel__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/ActivitySector__c.field-meta.xml
<CustomField>
    <fullName>ActivitySector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de Distribuição</label>
    <referenceTo>ActivitySector__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CodigoSap__c.field-meta.xml
<CustomField>
    <fullName>CodigoSap__c</fullName>
    <externalId>true</externalId>
    <label>Número do Pedido App</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Cultura__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de Distribuição</label>
    <referenceTo>DistributionChannel__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Incoterms2__c.field-meta.xml
<CustomField>
    <fullName>Incoterms2__c</fullName>
    <label>Incoterms 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/OrderReason__c.field-meta.xml
<CustomField>
    <fullName>OrderReason__c</fullName>
    <label>Motivo da Ordem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>Visita</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Contato estabelecido em feira comercial</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Anúncio de televisão</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>Recomendação de cliente</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Publicidade de jornal</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>Preço excelente</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>Fornecimento rápido</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>Bom serviço</label>
            </value>
            <value>
                <fullName>009</fullName>
                <label>Devolução acelerada</label>
            </value>
            <value>
                <fullName>100</fullName>
                <label>Diferença de preço: preço alto demais</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>Fraca qualidade</label>
            </value>
            <value>
                <fullName>102</fullName>
                <label>Danificado em trânsito</label>
            </value>
            <value>
                <fullName>103</fullName>
                <label>Diferença de quantidades</label>
            </value>
            <value>
                <fullName>104</fullName>
                <label>Mercadoria deteriorada</label>
            </value>
            <value>
                <fullName>105</fullName>
                <label>Amostra gratuita</label>
            </value>
            <value>
                <fullName>200</fullName>
                <label>Diferença preço: preço demasiado baixo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipName>PedidosCondicao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente Entrega</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/StatusSAP__c.field-meta.xml
<CustomField>
    <fullName>StatusSAP__c</fullName>
    <label>Status SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Em análise de Crédito</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Crédito Bloqueado</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Crédito Liberado</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Concluído</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Faturado Parcialmente</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Safra__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código da Safra</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingDivison__c/ShippingDivison__c.object-meta.xml
<CustomObject>
    
    <label>Divisão de Remessa</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Divisão de Remessa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Divisões de Remessa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingDivison__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Data de Entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShippingDivison__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ShippingDivison__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Divisões de Remessa</relationshipLabel>
    <relationshipName>DivisoesRemessa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingDivison__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Qauntidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalloutOrder.cls
public with sharing class CalloutOrder {
    public CalloutOrder() {
        
    }

    public static IntegrationUtils.CalloutResponse processIntegration(Id orderId){

		Order parentOrder = [SELECT Id, CodigoSap__c, Type, SalesOrg__r.SalesOrganizationCode__c, DistributionChannel__c, 
                            ActivitySector__c, Incoterms__c, Incoterms2__c, PaymentCondition__c, OrderReason__c , 
                            OrderNumber, Crop__r.Code__c, Culture__r.Codigo__c, EndDate, TotalAmount, 
                            Currency__c, (SELECT Id FROM OrderItems) 
                            FROM Order WHERE Id = :orderId];
		
		List<Order> allOrders = new List<Order>{parentOrder};
		
		IntegrationUtils.CalloutResponse calloutResponse = sendOrder(allOrders);

		if (calloutResponse.success) {
			
			ResponseParameters resp = (ResponseParameters) calloutResponse.parsedResponse;
			
			Map<String, Order> orderMap = new Map<String, Order>();

			for (Order ord : allOrders) {
				orderMap.put(ord.OrderNumber, ord);
			}

			List<Order> orderList = new List<Order>();

			for (ResponseParametersWrapper respWrapper : resp.responses) {
				if (orderMap.containsKey(respWrapper.OrderNumber)) {

					Order ord = orderMap.get(respWrapper.OrderNumber);
                    ord.CodigoSap__c = respWrapper.DetalhesPedido[0].NumeroOrdemVenda; 
                    ord.StatusSAP__c = respWrapper.DetalhesPedido[0].StatusSap;
                    // ord.TypeMessage__c = respWrapper.Mensagens[0].Tipo;
                    // ord.Message__c = respWrapper.Mensagens[0].Mensagem;
					orderList.add(ord);
				}
			}

			if (!orderList.isEmpty()) {
				update orderList;
			}
		}
		
		return calloutResponse;
	}

	public static IntegrationUtils.CalloutResponse sendOrder(List<Order> orders) {
			
		List<RequestParameters> request = new List<RequestParameters>();

		for (Order ord : orders) {
			request.add(new RequestParameters(ord));
		}

		String payload = JSON.serialize(request);

		//Metodo para busca de Access Token, depende de cada projeto, podendo estar presente dentro de uma custom settings ou relacionado com outra requisição.
		String accessToken = '';//! FALTA SABER A RESPOSTA DO SAP QUANTO A AUTENTICAÇÃO! F
		
		//Path geralmente cadastrado dentro de ua customSettings
		String endpoint = (!Test.isRunningTest() ? 'callout:HANA_Oncoprod/PrePedido_SFOut' : 'http://callout.My_Named_Credential.com/some/path');
		Map<String, String> headersMap = new Map<String, String>();
		headersMap.put('Content-type', 'application/json');
		headersMap.put('Authorization', 'Bearer '+ accessToken);
		
		IntegrationUtils.RequestResponseObject responseObject = IntegrationUtils.executeCallout(endpoint, payload, headersMap);

		if (responseObject.success) {

			HttpResponse response = responseObject.response;

            IntegrationLog.createLog('Pedido OUT', 'OUT', response.getBody(), payload, false);
			// .WSLog('Pedido', 'OUTBOUND', response.getBody(), payload, false);
			try {

				List<ResponseParametersWrapper> responses = (List<ResponseParametersWrapper>) JSON.deserialize(response.getBody(), List<ResponseParametersWrapper>.class);
				return new IntegrationUtils.CalloutResponse(new ResponseParameters(responses));
			} catch (Exception e) {
				
				String defaultErrorMessage = 'Malformatted HTTP Response Exception: ' + e.getMessage();

				return new IntegrationUtils.CalloutResponse(defaultErrorMessage);
			}
		} else {

            IntegrationLog.createLog('Pedido OUT', 'OUT', responseObject.exceptionObject.getMessage(), payload, true);
			return new IntegrationUtils.CalloutResponse(responseObject.exceptionObject.getMessage());
		}
    }

    //! Preparing data to Callout
    public class RequestParameters{
        public Object header;
        public List<CalloutOrder.PartnerParameters> partner;
        public List<CalloutOrder.ScheduleParameters> schedule;
        public List<CalloutOrder.ConditionParameters> condition;
        public List<CalloutOrder.OrderItemParameters> orderItems;

        public RequestParameters(Order order){

            partner = new List<CalloutOrder.PartnerParameters>();
            schedule = new List<CalloutOrder.ScheduleParameters>();
            orderItems = new List<CalloutOrder.OrderItemParameters>();
            condition = new List<CalloutOrder.ConditionParameters>();
            partner.add(new CalloutOrder.PartnerParameters(order.AccountId, 'EO'));
            partner.add(new CalloutOrder.PartnerParameters(order.ShippingAccount__c, 'RM'));

            Set<Id> orderItemIds = new Set<Id>();

            if(order.CodigoSap__c == null){
                CalloutOrder.HeaderInsert header = new CalloutOrder.HeaderInsert();
                header.orderSalesType = order.Type; // Não esquecer de mudar isso
                header.salesOrg = order.SalesOrg__r.SalesOrganizationCode__c;
                header.distributionChannel = order.DistributionChannel__c;
                header.activitySector = order.ActivitySector__c;
                header.incoterms1 = order.Incoterms__c;
                header.incoterms2 = order.Incoterms2__c;
                header.paymentCondition = order.PaymentCondition__c;
                header.orderReason = order.OrderReason__c;
                header.codSap = order.OrderNumber;
                header.crop = order.Crop__r.Code__c;
                header.culture = Integer.valueOf(order.Culture__r.Codigo__c);
                header.orderType = order.Type;
                header.codSalesforce = order.OrderNumber;
                header.expiredDate = order.EndDate;
            }
            else {
                CalloutOrder.HeaderUpdate header = new CalloutOrder.HeaderUpdate();
                header.codSap = order.CodigoSap__c;
                header.codSalesforce = order.OrderNumber;
                header.expiredDate = order.EndDate;
            }

            for(OrderItem orderItem : order.OrderItems){
                orderItemIds.add(orderItem.Id);
            }

            Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>([
                SELECT Id, Product2.ExternalId__c, Product2.DistributionCenter__r.Code__c, Quantity
                FROM OrderItem
                WHERE Id IN: orderItemIds
            ]);

            List<ShippingDivison__c> divisonList = [SELECT Id,Name, DeliveryDate__c, Quantity__c, OrderItem__c FROM ShippingDivison__c WHERE OrderItem__c IN: orderItemIds];
            Map<Id, List<ShippingDivison__c>> divisionMap = new  Map<Id, List<ShippingDivison__c>>();

            for(ShippingDivison__c sd : divisonList){
                if(!divisionMap.containsKey(sd.OrderItem__c)){
                    divisionMap.put(sd.OrderItem__c, new List<ShippingDivison__c>());
                }
                divisionMap.get(sd.OrderItem__c).add(sd);
            }

            List<Integer> shippingCodesList = new List<Integer>();
            for(OrderItem orderItem : orderItemMap.values()){

                shippingCodesList.clear();
                for(ShippingDivison__c sd : divisionMap.get(orderItem.Id)){
                    shippingCodesList.add(Integer.valueOf(sd.Name));
                    schedule.add(new CalloutOrder.ScheduleParameters(Integer.valueOf(sd.Name), sd.Quantity__c, sd.DeliveryDate__c));
                }
                orderItems.add(new CalloutOrder.OrderItemParameters(orderItem, shippingCodesList));
            }

            condition.add(new CalloutOrder.ConditionParameters(Integer.valueOf(order.Culture__r.Codigo__c), 'PR00', order.TotalAmount, order.Currency__c)); 
        }
    }

    public class HeaderInsert{
        public String orderSalesType;
        public String salesOrg;
        public String distributionChannel;
        public String activitySector;
        public String incoterms1;
        public String incoterms2;
        public String paymentCondition;
        public String orderReason;
        public String codSap;
        public String crop;
        public Integer culture;
        public String orderType;
        public String codSalesforce;
        public Date  expiredDate;

        public HeaderInsert(){}
    }

    public class HeaderUpdate{
        public String codSap;
        public String codSalesforce;
        public Date  expiredDate;

        public HeaderUpdate(){}
    }

    public class PartnerParameters{
        public String partnerFunc;
        public String partnerCode;

        public PartnerParameters(String partnerCode, String partnerFunc){
            this.partnerCode = partnerCode;
            this.partnerFunc = partnerFunc;
        }
    } 

    public class ScheduleParameters{
        public Integer incrementItem;
        public Decimal quantityItem;
        public Date deliveryDate;

        public ScheduleParameters(Integer incrementItem, Decimal quantityItem, Date deliveryDate){
            this.incrementItem = incrementItem;
            this.quantityItem = quantityItem;
            this.deliveryDate = deliveryDate;
        }
    }

    public class ConditionParameters{
        public Integer incrementItem;
        public String conditionType;
        public Decimal conditionValue;
        public String conditionCurrency;

        public ConditionParameters(Integer incrementItem, String conditionType, Decimal conditionValue, String conditionCurrency){
            this.incrementItem = incrementItem;
            this.conditionType = conditionType;
            this.conditionValue = conditionValue;
            this.conditionCurrency = conditionCurrency;
        }
    }

    public class OrderItemParameters{
        public List<Integer> incrementItem;
        public String material;
        public String center;
        public Decimal quantityItem;

        public OrderItemParameters(OrderItem orderItem, List<Integer> shippingDivison){
            this.incrementItem = new List<Integer>(shippingDivison);
            this.material = orderItem.Product2.ExternalId__c;
            this.center = orderItem.Product2.DistributionCenter__r.Code__c;
            this.quantityItem = orderItem.Quantity;
        }
    }

    public class ResponseParameters {
        public List<ResponseParametersWrapper> responses;

        public ResponseParameters(List<ResponseParametersWrapper> responses) {
            this.responses = responses;
        }
    }


    //! Response part
    public class ResponseParametersWrapper {
        public String OrderNumber; 
        public List<OrderDetails> DetalhesPedido;
        public List<Messages> Mensagens; 
    }

    public class Messages{
        public String Tipo;
        public String Mensagem;
    }

    public class OrderDetails{
        public String StatusSap;
        public String NumeroOrdemVenda;
    }
}