force-app/main/default/objects/ActivitySector__c/ActivitySector__c.object-meta.xml
<CustomObject>
    <label>Setor de Atividade</label>
    <nameField>
        <label>Setor de Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Setor de Atividade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Empresas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/ActivitySector__c.field-meta.xml
<CustomField>
    <fullName>ActivitySector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Setor de Atividade</label>
    <referenceTo>ActivitySector__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/ClientGroup__c.field-meta.xml
<CustomField>
    <fullName>ClientGroup__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NÃO SEGMENTADO</fullName>
            </value>
            <value>
                <fullName>REDISTRIBUIÇÃO</fullName>
            </value>
            <value>
                <fullName>MODULAR</fullName>
            </value>
            <value>
                <fullName>CLÁSSICO</fullName>
            </value>
            <value>
                <fullName>INOVADOR</fullName>
            </value>
            <value>
                <fullName>CLUBE A</fullName>
            </value>
            <value>
                <fullName>CONECTA</fullName>
            </value>
            <value>
                <fullName>DINAMICO</fullName>
                <label>DINÂMICO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de Distribuição</label>
    <referenceTo>DistributionChannel__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/SupplierCenter__c.field-meta.xml
<CustomField>
    <fullName>SupplierCenter__c</fullName>
    <label>Centro Fornecedor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DistributionChannel__c/DistributionChannel__c.object-meta.xml
<CustomObject>
    <label>Canal de Distribuição</label>
    <nameField>
        <label>Canal de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <label>Escritório Venda</label>
    <nameField>
        <label>Nome do Escritório Venda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritório Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Equipe de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CompaniesRelatedToAccountController.cls
public class CompaniesRelatedToAccountController {
    @AuraEnabled
    public static String getCompanies(String accountId) {
        List<CompanyData> companies = new List<CompanyData>();
        for (Company__c company : [
            SELECT Id,
                   Name,
                   SalesOrg__r.Name,
                   SalesOffice__r.Name,
                   SalesTeam__r.Name,
                   ActivitySector__r.Name,
                   DistributionChannel__r.Name,
                   ClientGroup__c,
                   SupplierCenter__c
              FROM Company__c
             WHERE Conta__c =: accountId
        ]) {
            CompanyData companyData = new CompanyData();
            companyData.id = company.Id != null ? company.Id : '';
            companyData.name = company.Name != null ? company.Name : '';
            companyData.salesOrg = company.SalesOrg__r.Name != null ? company.SalesOrg__r.Name : '';
            companyData.salesOffice = company.SalesOffice__r.Name != null ? company.SalesOffice__r.Name : '';
            companyData.salesTeam = company.SalesTeam__r.Name != null ? company.SalesTeam__r.Name : '';
            companyData.activitySector = company.ActivitySector__r.Name != null ? company.ActivitySector__r.Name : '';
            companyData.distributionChannel = company.DistributionChannel__r.Name != null ? company.DistributionChannel__r.Name : '';
            companyData.clientGroup = company.ClientGroup__c != null ? company.ClientGroup__c : '';
            companyData.supplierCenter = company.SupplierCenter__c != null ? company.SupplierCenter__c : '';
            companies.add(companyData);
        }

        return JSON.serialize(companies);
    }

    public class CompanyData {
        public String id;
        public String name;
        public String salesOrg;
        public String salesOffice;
        public String salesTeam;
        public String activitySector;
        public String distributionChannel;
        public String clientGroup;
        public String supplierCenter;
    }
}