force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Log de Integração</label>
    <nameField>
        <displayFormat>LOG{0000000000}</displayFormat>
        <label>Log de Integração Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de integrações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeOfMonths__c/TimeOfMonths__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting para número de meses para limpar logs</description>
    <label>Tempo em meses</label>
</CustomObject>

force-app/main/default/objects/TimeOfMonths__c/fields/NumberOfMonths__c.field-meta.xml
<CustomField>
    <fullName>NumberOfMonths__c</fullName>
    <length>255</length>
    <label>Número de meses</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchDeleteIntegrationLogsTest.cls
@isTest
public with sharing class BatchDeleteIntegrationLogsTest {
    public BatchDeleteIntegrationLogsTest() {}

    @TestSetup
    public static void testSetup() {
        TimeOfMonths__c time = new TimeOfMonths__c(
            Name = 'Log de Integrações',
            NumberOfMonths__c = '3'
        );

        INSERT time;
            
        //Creating integration log
        IntegrationLog.createLog('Teste', 'OUT', '', 'Integração para Batch', true);

            
    }
    @isTest
    public static void testMethod1(){
        IntegrationLog__c log = [SELECT Id FROM IntegrationLog__c LIMIT 1];
        Datetime lastMonths = Datetime.now().addMonths(-5);
        Test.setCreatedDate(log.Id, lastMonths);

        Test.startTest();
        BatchDeleteIntegrationLogs.run();
        Test.stopTest();
    }
    @isTest
    public static void testQueryIntegrationSchedulable(){
        BatchDeleteIntegrationLogs.scheduleBatch();
    }
}