force-app/main/default/objects/Commodity__c/Commodity__c.object-meta.xml
<CustomObject>
    <label>Commodity</label>
    <nameField>
        <label>Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commodities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commodity__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>Código</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/CommodityPrice__c.object-meta.xml
<CustomObject>
    <label>Preço Commodities</label>
    <nameField>
        <label>Preço Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preços Commodities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommodityPrice__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipLabel>Preços Commodities</relationshipLabel>
    <relationshipName>CommoditiesPricelist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/CreatedByUser__c.field-meta.xml
<CustomField>
    <fullName>CreatedByUser__c</fullName>
    <label>Criado Por</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda de cotação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <label>Dólar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/MarketIdentifierCode__c.field-meta.xml
<CustomField>
    <fullName>MarketIdentifierCode__c</fullName>
    <label>Código de Identificação do Mercado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XCBOT</fullName>
                <label>Bolsa Chicago</label>
            </value>
            <value>
                <fullName>PROV</fullName>
                <label>Balcão Provisório</label>
            </value>
            <value>
                <fullName>Praça</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/MaturityKeyDate__c.field-meta.xml
<CustomField>
    <fullName>MaturityKeyDate__c</fullName>
    <label>Data Fixada de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/PriceQuotationCurrency__c.field-meta.xml
<CustomField>
    <fullName>PriceQuotationCurrency__c</fullName>
    <label>Preço da cotação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/PriceQuotationTime__c.field-meta.xml
<CustomField>
    <fullName>PriceQuotationTime__c</fullName>
    <label>Hora da Cotação</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/PriceQuotationType__c.field-meta.xml
<CustomField>
    <fullName>PriceQuotationType__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>09</fullName>
                <label>Bolsa</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Balcão</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/QuotationDate__c.field-meta.xml
<CustomField>
    <fullName>QuotationDate__c</fullName>
    <label>Data da cotação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/TimeToMaturity__c.field-meta.xml
<CustomField>
    <fullName>TimeToMaturity__c</fullName>
    <label>Vencimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JAN</fullName>
                <label>Janeiro</label>
            </value>
            <value>
                <fullName>FEB</fullName>
                <label>Fevereiro</label>
            </value>
            <value>
                <fullName>MAR</fullName>
                <label>Março</label>
            </value>
            <value>
                <fullName>APR</fullName>
                <label>Abril</label>
            </value>
            <value>
                <fullName>MAY</fullName>
                <label>Maio</label>
            </value>
            <value>
                <fullName>JUN</fullName>
                <label>Junho</label>
            </value>
            <value>
                <fullName>JUL</fullName>
                <label>Julho</label>
            </value>
            <value>
                <fullName>AUG</fullName>
                <label>Agosto</label>
            </value>
            <value>
                <fullName>SEP</fullName>
                <label>Setembro</label>
            </value>
            <value>
                <fullName>OCT</fullName>
                <label>Outubro</label>
            </value>
            <value>
                <fullName>NOV</fullName>
                <label>Novembro</label>
            </value>
            <value>
                <fullName>DEC</fullName>
                <label>Dezembro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/UnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasure__c</fullName>
    <label>Unidade de medida de cotação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BU</fullName>
                <label>Bushel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommodityPrice__c/fields/ValidityStart_DateTime__c.field-meta.xml
<CustomField>
    <fullName>ValidityStart_DateTime__c</fullName>
    <label>Válido desde</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/IntegrationINCommodityPrice.cls
@RestResource(urlMapping='/upsertCommodityPrice/*')
global with sharing class IntegrationINCommodityPrice {

    @HttpPost
    global static TemplateDataIntegrationFields.CommodityPriceResponseModel upsertCommodityPrice(String request) {
        TemplateDataIntegrationFields.CommodityPriceResponseModel response = new TemplateDataIntegrationFields.CommodityPriceResponseModel();
        try {
            List<TemplateDataIntegrationFields.CommodityPriceINData> commodityPriceINData = (List<TemplateDataIntegrationFields.CommodityPriceINData>) JSON.deserialize(request, List<TemplateDataIntegrationFields.CommodityPriceINData>.class);
            Set<String> commoditiesExternalId = new Set<String>();
            for (TemplateDataIntegrationFields.CommodityPriceINData commodityPrice : commodityPriceINData) {
                commoditiesExternalId.add(commodityPrice.derivativeContrSpecification);
            }

            Map<String, Commodity__c> commoditiesByExternalId = new Map<String, Commodity__c>();
            for (Commodity__c commodity : [
                SELECT Id,
                       ExternalId__c
                  FROM Commodity__c
                 WHERE ExternalId__c IN: commoditiesExternalId
            ]) {
                commoditiesByExternalId.put(commodity.ExternalId__c, commodity);
            }

            List<CommodityPrice__c> commodityPriceList = new List<CommodityPrice__c>();
            for (TemplateDataIntegrationFields.CommodityPriceINData commodityPrice : commodityPriceINData) {
                Id commodityId = commoditiesByExternalId.get(commodityPrice.derivativeContrSpecification).Id;
                commodityPriceList.add(new CommodityPrice__c(
                    Commodity__c = commodityId,
                    CreatedByUser__c = commodityPrice.createdByUser,
                    Currency__c = commodityPrice.priceCurrency,
                    MarketIdentifierCode__c = commodityPrice.marketIdentifierCode,
                    MaturityKeyDate__c = commodityPrice.maturityKeyDate,
                    PriceQuotationCurrency__c = commodityPrice.priceQuotation,
                    PriceQuotationTime__c = commodityPrice.priceQuotationTime,
                    PriceQuotationType__c = commodityPrice.priceQuotationType,
                    QuotationDate__c = commodityPrice.priceQuotationDate,
                    TimeToMaturity__c = commodityPrice.timeToMaturity,
                    UnitOfMeasure__c = commodityPrice.unitOfMeasure,
                    ValidityStart_DateTime__c = commodityPrice.validityStartUtcDatetime,
                    ExternalId__c = commodityPrice.priceQuotationDate + '-' + commodityPrice.derivativeContrSpecification + '-' + commodityPrice.marketIdentifierCode
                ));
            }

            Boolean hasErrors = false;
            List<Database.UpsertResult> upsertRecords = Database.upsert(commodityPriceList, CommodityPrice__c.Fields.ExternalId__c, false);
            for (Database.UpsertResult result : upsertRecords){
                if(!result.isSuccess()){
                    hasErrors = true;
                    for (Database.error error: result.getErrors()){
                        response.message += '\n' + error.getMessage();
                    }
                }
            }

            if (hasErrors) {
                System.debug('Erro: ' + JSON.serialize(response));
                IntegrationLog.createLog('Preço Commodities IN', 'IN', JSON.serialize(request), JSON.serialize(response), true);
            } else {
                response.message = 'Sucesso!';
                IntegrationLog.createLog('Preço Commodities IN', 'IN', JSON.serialize(request), JSON.serialize(response), false);
            }
        } catch (Exception ex) {
            response.message = 'Error: ' + ex.getMessage() + '   -   ' + ex.getStackTraceString();
            System.debug('response.message: ' + response.message);
            IntegrationLog.createLog('Preço Commodities IN', 'IN', JSON.serialize(request), response.message, true);
        }

        return response;
    }
}