force-app/main/default/objects/VisitPlanning__c/VisitPlanning__c.object-meta.xml
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Planejamento da Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamento de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data Fim do Plano</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>Horário Final</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/InitialDate__c.field-meta.xml
<CustomField>
    <fullName>InitialDate__c</fullName>
    <label>Data de Início do Plano</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Horário Inicial</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/VisitSeller__c.field-meta.xml
<CustomField>
    <fullName>VisitSeller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CTV da Visita</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Planejamento_de_Visitas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CalendarHelper.cls
public with sharing class CalendarHelper {
    public CalendarHelper() {
            //
    }

    private static Boolean isEnabled;

    static{
        isEnabled = true;
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }


    public static void createCalendarEvent(List<VisitPlanning__c> visitPlanningList) {
        //List<SObject_Visit> visitList = new List<SObject_Visit>();
        List<Event> eventList = new List<Event>();

        for(VisitPlanning__c visitPlanning : visitPlanningList){
            //if()//DateTime.newInstance(withDate.date(), withTime.time())
            Long dt1Long = DateTime.newInstance(visitPlanning.InitialDate__c, visitPlanning.StartTime__c).getTime();
            System.debug('dt1Long ' + dt1Long);
			Long dt2Long = DateTime.newInstance(visitPlanning.EndDate__c, visitPlanning.EndTime__c).getTime();
            System.debug('dt2Long ' + dt2Long);
			Long milliseconds = dt2Long - dt1Long;
            System.debug('milliseconds ' + milliseconds);
			Long seconds = milliseconds / 1000;
            System.debug('seconds ' + seconds);
			Long minutes = seconds / 60;
            System.debug('minutes ' + minutes);
            Event event = new Event(Subject = 'Meeting', DurationInMinutes = integer.valueOf(minutes), OwnerId =  visitPlanning.VisitSeller__c, StartDateTime = DateTime.newInstance(visitPlanning.InitialDate__c, visitPlanning.StartTime__c), EndDateTime = DateTime.newInstance(visitPlanning.EndDate__c, visitPlanning.EndTime__c));
            eventList.add(event);
        }

        upsert eventList;
    }
}