force-app/main/default/objects/Delimitadores__c/Delimitadores__c.object-meta.xml
<CustomObject>
    <label>Delimitadores</label>
    <nameField>
        <label>Delimitadores Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delimitadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delimitadores__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo para controle de identificação do registro.</description>
    <externalId>true</externalId>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Delimitadores__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Safra__c</referenceTo>
    <relationshipLabel>Delimitadores</relationshipLabel>
    <relationshipName>Delimitadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delimitadores__c/fields/SalesCondition__c.field-meta.xml
<CustomField>
    <fullName>SalesCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de Preços</label>
    <referenceTo>SalesCondition__c</referenceTo>
    <relationshipLabel>Delimitadores</relationshipLabel>
    <relationshipName>Delimitadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delimitadores__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Venda</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Delimitadores</relationshipLabel>
    <relationshipName>Delimitadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotaFiscal__c/NotaFiscal__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal</label>
    <nameField>
        <label>Nota Fiscal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NotaFiscal__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Safra__c/Safra__c.object-meta.xml
<CustomObject>
    <label>Safra</label>
    <nameField>
        <label>Safra Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesCondition__c/SalesCondition__c.object-meta.xml
<CustomObject>
    <label>Condição de Vendas</label>
    <nameField>
        <label>Condição de Vendas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Organização de Venda</label>
    <nameField>
        <label>Nome da Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organização de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationINCropDelimitation.cls
@RestResource(urlMapping='/upsertCropDelimitation/*')
global with sharing class IntegrationINCropDelimitation {

    @HttpPost
    global static ResponseModel upsertCropDelimitation(List<TemplateDataIntegrationFields.DelimitadoresINData> request) {

        Map<String, Id> lookups = new Map<String, Id>();
        Set<String> safraLookups = new Set<String>();
        Set<String> salesOrgLookups = new Set<String>();
        Set<String> salesConditionLookups = new Set<String>();
        

    
        List<TemplateDataIntegrationFields.ResponseParent> responseList = new List<TemplateDataIntegrationFields.ResponseParent>();
        List<Delimitadores__c> delimitadoresListToUpsert = new List<Delimitadores__c>();
        
  
        for (TemplateDataIntegrationFields.DelimitadoresINData delimitator : request){
            safraLookups.add(delimitator.Safra);
            salesOrgLookups.add(delimitator.SalesOrganization);
            salesConditionLookups.add(delimitator.PriceList);
        }
        

        for (Safra__c safra : [SELECT Id, Code__c FROM Safra__c WHERE Code__c IN : safraLookups]) {
            lookups.put('Safra__c' + safra.Code__c, safra.Id);
            //lookups.put('SafraName' + safra.Code__c, safra.Name);
        }
        for (SalesOrg__c salesOrg : [SELECT Id, SalesOrganizationCode__c FROM SalesOrg__c WHERE SalesOrganizationCode__c IN : salesOrgLookups]) {
            lookups.put('SalesOrg__c' + salesOrg.SalesOrganizationCode__c, salesOrg.Id);
        }
        for (SalesCondition__c salesCondition : [SELECT Id, ExternalId__c FROM SalesCondition__c WHERE  ExternalId__c IN : salesConditionLookups]){
            lookups.put('SalesCondition__c' + salesCondition.ExternalId__c, salesCondition.Id);
        }
       
        for (TemplateDataIntegrationFields.DelimitadoresINData delimitator : request){
            delimitator.Name = 'teste';
            delimitator.DelimitadoresExternalId = delimitator.Safra + delimitator.PriceList + delimitator.SalesOrganization;
        }
        
        FactoryDataIntegration.convertSObject(new Delimitadores__c(), 'IN', request, responseList, delimitadoresListToUpsert, lookups);
        System.debug('delimitadoresListToUpsert First' + delimitadoresListToUpsert);  

		IntegrationUtils.upsertRecords(
            Database.upsert(delimitadoresListToUpsert, Delimitadores__c.ExternalId__c, false), 
            responseList, 
            delimitadoresListToUpsert, 
            NotaFiscal__c.ExternalId__c
        );
        System.debug('delimitadoresListToUpsert' + delimitadoresListToUpsert);

        //Checking integration errors to log
        // Verifica erros de integração para o log
        Boolean hasError = false;

        for(TemplateDataIntegrationFields.ResponseParent responseInvoice : responseList){
            if(responseInvoice.status == false){
                hasError = true;
                break;
            }
        }
		
        //Creating integration log
        IntegrationLog.createLog('Safra Delimitadores - DataLake', 'IN', JSON.serialize(request), JSON.serialize(responseList), hasError);
        
        //Returning response
         // Retorna a resposta Outbound
        ResponseModel modelo = new ResponseModel();
        modelo.response = responseList;
        return modelo;
    }
    // Classe que cria a resposta
    global class ResponseModel {

        List<TemplateDataIntegrationFields.ResponseParent> response;

        public ResponseModel(List<TemplateDataIntegrationFields.ResponseParent> response) {

            this.response = response;
            
        }
        public ResponseModel() {   
            this.response = new List<TemplateDataIntegrationFields.ResponseParent>();         
        }
    }
}