force-app/main/default/objects/Fotos__c/Fotos__c.object-meta.xml
<CustomObject>
    <label>Foto</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Fotos Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fotos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fotos__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/Observation__c.field-meta.xml
<CustomField>
    <fullName>Observation__c</fullName>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/RTR__c.field-meta.xml
<CustomField>
    <fullName>RTR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTR</label>
    <referenceTo>TechnicalReport__c</referenceTo>
    <relationshipLabel>Fotos</relationshipLabel>
    <relationshipName>Fotos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/TechnicalReport__c.object-meta.xml
<CustomObject>
    <description>RTR</description>
    <label>Relatório Técnico</label>
    <nameField>
        <displayFormat>RTR-{0000}</displayFormat>
        <label>Relatório Técnico Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relatórios Técnicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalReport__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PhotosToReportController.cls
public without sharing class PhotosToReportController {
    public PhotosToReportController() {}

    @AuraEnabled
    public static String createPhoto(String base64, String filename, String rtrId, String observation){
        String externalIdRtr = [SELECT ExternalId__c FROM TechnicalReport__c WHERE Id =: rtrId LIMIT 1].ExternalId__c;
        Integer numberPhotos = [SELECT COUNT() FROM Fotos__c WHERE RTR__c =: rtrId];
        Fotos__c photo = new Fotos__c(
            ExternalId__c = externalIdRtr + '_' + (++numberPhotos),
            Observation__c = observation,
            RTR__c = rtrId
        );

        INSERT photo;

        String response = uploadFile(base64, filename, photo.Id);
        return response;
        
    }

    private static String uploadFile(String base64, String filename, String recordId) {
        ContentVersion cv = createContentVersion(base64, filename);
        ContentDocumentLink cdl = createContentLink(cv.Id, recordId);
        if (cv == null || cdl == null) { return null; }
        return cdl.Id;
    }

    private static ContentVersion createContentVersion(String base64, String filename) {
        ContentVersion cv = new ContentVersion();
        cv.VersionData = EncodingUtil.base64Decode(base64);
        cv.Title = filename;
        cv.PathOnClient = filename;
        try {
            insert cv;
            return cv;
        } catch(DMLException e) {
            System.debug(e);
            return null;
        }
    }

    private static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
        if (contentVersionId == null || recordId == null) { return null; }
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id =: contentVersionId
        ].ContentDocumentId;
        cdl.LinkedEntityId = recordId;
        cdl.ShareType = 'V';
        
        try {
            insert cdl;
            return cdl;
        } catch(DMLException e) {
            System.debug(e);
            return null;
        }
    }
}