force-app/main/default/objects/Fotos__c/Fotos__c.object-meta.xml
<CustomObject>
    <label>Foto</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Fotos Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fotos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fotos__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/FotoControl__c.field-meta.xml
<CustomField>
    <fullName>FotoControl__c</fullName>
    <label>Foto Item</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/IsIntegrated__c.field-meta.xml
<CustomField>
    <fullName>IsIntegrated__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lembrete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fotos__c/fields/RTR__c.field-meta.xml
<CustomField>
    <fullName>RTR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTR</label>
    <referenceTo>TechnicalReport__c</referenceTo>
    <relationshipLabel>Fotos</relationshipLabel>
    <relationshipName>Fotos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/TechnicalReport__c.object-meta.xml
<CustomObject>
    <description>RTR</description>
    <label>Relatório Técnico</label>
    <nameField>
        <displayFormat>RTR-{0000}</displayFormat>
        <label>Relatório Técnico Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relatórios Técnicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalReport__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/VisitPlanning__c.field-meta.xml
<CustomField>
    <fullName>VisitPlanning__c</fullName>
    <label>Visita</label>
    <referenceTo>VisitPlanning__c</referenceTo>
    <relationshipLabel>Relatórios Técnicos</relationshipLabel>
    <relationshipName>Relatorios_Tecnicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/VisitPlanning__c.object-meta.xml
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Planejamento da Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamento de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <displayFormat>{000000000}</displayFormat>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/fields/RTR__c.field-meta.xml
<CustomField>
    <fullName>RTR__c</fullName>
    <label>RTR Gerado</label>
    <summaryFilterItems>
        <field>TechnicalReport__c.Status__c</field>
        <operation>equals</operation>
        <value>Gerado</value>
    </summaryFilterItems>
    <summaryForeignKey>TechnicalReport__c.VisitPlanning__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/FotosHelper.cls
public without sharing class FotosHelper {
    
    private static Boolean isEnabled;

    static{
        isEnabled = true;
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }
    public static void isIntegrated(List<Fotos__c> fotosList, Boolean isToIntegrate){
        for(Fotos__c foto : fotosList){
            foto.IsIntegrated__c = isToIntegrate;
        }
    }
    public static void callVisitsIntegration(List<Fotos__c> fotosList){
        List<String> technicalRecordsIdList = new List<String>();
        List<String> visitIdList = new List<String>();
        for(Fotos__c foto : fotosList){
            technicalRecordsIdList.add(foto.RTR__c);
        }
        List<TechnicalReport__c> technicalRecordsList = new List<TechnicalReport__c>([SELECT Id, VisitPlanning__c FROM TechnicalReport__c WHERE Id IN: technicalRecordsIdList]);
        for(TechnicalReport__c technical : technicalRecordsList){
            visitIdList.add(technical.VisitPlanning__c);
        }
        CalloutVisits.callIntegration(visitIdList);    
    }
    public static void incrementItem(List<Fotos__c> fotosList){

        List<string> rtrList = new List<String>();

        for(Fotos__c fot: fotosList){
            rtrList.add(fot.RTR__c);
        }

        List<Fotos__c> fotsList = new List<Fotos__c>([SELECT Id, FotoControl__c, RTR__c FROM Fotos__c WHERE RTR__c IN: rtrList Order By FotoControl__c DESC LIMIT 1]);
        List<TechnicalReport__c> techReportList = new List<TechnicalReport__c>([SELECT Id, ExternalId__c FROM TechnicalReport__c WHERE Id IN: rtrList]);

        Map<String, String> mapTechnicalReport = new Map<String, String>();

        for(TechnicalReport__c fotosControl:  techReportList){
            mapTechnicalReport.put(fotosControl.Id, fotosControl.ExternalId__c);
        }

        Map<String, Fotos__c> fotosMap = new Map <String, Fotos__c>();

        for(Fotos__c fotosIncrement: fotsList){
            fotosMap.put(fotosIncrement.RTR__c, fotosIncrement);
        }

        for(Fotos__c fotosIncrement: fotosList){
            String rtr = mapTechnicalReport.get(fotosIncrement.RTR__c);
            
            if(!fotosMap.containsKey(fotosIncrement.RTR__c)){
                fotosIncrement.FotoControl__c = 10;
                fotosIncrement.ExternalId__c = rtr+fotosIncrement.FotoControl__c;
            }
            else{
                Fotos__c fotosNew = fotosMap.get(fotosIncrement.RTR__c);
                fotosIncrement.FotoControl__c = (fotosNew.FotoControl__c + 10);
                fotosIncrement.ExternalId__c = rtr + fotosIncrement.FotoControl__c;
            }
        }
    }
}