force-app/main/default/objects/TechnicalReport__c/TechnicalReport__c.object-meta.xml
<CustomObject>
    <description>RTR</description>
    <label>Relatório Técnico</label>
    <nameField>
        <displayFormat>RTR-{0000}</displayFormat>
        <label>Relatório Técnico Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relatórios Técnicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalReport__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TechnicalReport__c/fields/VisitPlanning__c.field-meta.xml
<CustomField>
    <fullName>VisitPlanning__c</fullName>
    <label>Visita</label>
    <referenceTo>VisitPlanning__c</referenceTo>
    <relationshipLabel>Relatórios Técnicos</relationshipLabel>
    <relationshipName>Relatorios_Tecnicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisitPlanning__c/VisitPlanning__c.object-meta.xml
<CustomObject>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Planejamento da Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamento de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitPlanning__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <displayFormat>{000000000}</displayFormat>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/IntegrationINTechnicalReport.cls
global with sharing class IntegrationINTechnicalReport {

    
    global static Map<String, List<TemplateDataINtegrationFields.Response>> upsertTechnicalReport (List<TemplateDataINtegrationFields.TechnicalReportINData> request){

        Map<String, Id> lookups = new Map<String, Id>();
        Set<String> visitsLookup = new Set<String>();
        for(TemplateDataIntegrationFields.TechnicalReportINData report : request){

            visitsLookup.add(report.ExternalIdVisit);
        }
        for (VisitPlanning__c visit : [SELECT Id, ExternalId__c FROM VisitPlanning__c WHERE ExternalId__c IN: visitsLookup ]) {
            lookups.put('Visit' + visit.ExternalId__c, visit.Id);
        }

        Map<String, List<TemplateDataINtegrationFields.Response>> responseMap = new Map<String, List<TemplateDataIntegrationFields.Response>>();

        List<TechnicalReport__c> technicalReportListToUpsert = new List<TechnicalReport__c>();
	
        Map<String, String> parentMapKeys = new Map<String, String>();
        for(TemplateDataIntegrationFields.TechnicalReportINData report : request){
            parentMapKeys.put(report.ExternalIdVisit, lookups.containsKey('Visit'+report.ExternalIdVisit) ? String.valueOf(lookups.get('Visit'+report.ExternalIdVisit)) : report.ExternalIdVisit);
        }


        FactoryDataIntegration.convertSObjectChild(
            new TechnicalReport__c(),
            'IN',
            request,
            responseMap,
            technicalReportListToUpsert,
            lookups,
            parentMapKeys
        );
        TechnicalReportHelper.disableTrigger();
        List<Database.UpsertResult> upsResults = Database.upsert(technicalReportListToUpsert, TechnicalReport__c.ExternalId__c, false);
        System.debug('upsResults' + upsResults);
        IntegrationUtils.upsertChildRecords(upsResults, responseMap, technicalReportListToUpsert, TechnicalReport__c.ExternalId__c);
        TechnicalReportHelper.enableTrigger();
        return responseMap;
    }
}